// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcUVR3-vjtQq7w75dQ8ReOsyaKC1j9n84',
    appId: '1:595802795623:web:134a11664e56c777006ec2',
    messagingSenderId: '595802795623',
    projectId: 'majiku-5b07e',
    authDomain: 'majiku-5b07e.firebaseapp.com',
    storageBucket: 'majiku-5b07e.firebasestorage.app',
    measurementId: 'G-5CDBJJSTHM',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcUVR3-vjtQq7w75dQ8ReOsyaKC1j9n84',
    appId: '1:595802795623:web:c24594e5ae0c0ae0006ec2',
    messagingSenderId: '595802795623',
    projectId: 'majiku-5b07e',
    authDomain: 'majiku-5b07e.firebaseapp.com',
    storageBucket: 'majiku-5b07e.firebasestorage.app',
    measurementId: 'G-R4T7JD4WT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_x64PPVL-Lb518IPVQBcnZxUNfTXOsIQ',
    appId: '1:595802795623:android:44ee9233805a4ab4006ec2',
    messagingSenderId: '595802795623',
    projectId: 'majiku-5b07e',
    storageBucket: 'majiku-5b07e.firebasestorage.app',
  );

}