import '../models_daily_free/quote_model.dart';

List<Quote> relateQuotes = [
  Quote(
    text: "Niat hati ingin produktif, apa daya kasur lebih posesif.",
    textEn: "My mind wants to be productive, but my bed is too possessive.",
    author: "Netizen",
    category: "Relate",
  ),
  Quote(
    text: "Dewasa itu menjebak. Katanya bebas melakukan apa saja, ternyata bebas bayar tagihan apa saja.",
    textEn: "Adulthood is a trap. They said you're free to do anything, turns out you're just free to pay all kinds of bills.",
    author: "Netizen",
    category: "Relate",
  ),
  Quote(
    text: "Hobi rebahan, tapi cita-cita sukses jalur langit tanpa orang dalam.",
    textEn: "Hobby: Lying down. Goal: Successful through divine intervention without any inside connections.",
    author: "Kaum Rebahan",
    category: "Relate",
  ),
  Quote(
    text: "Diet itu mudah, yang susah itu menahan godaan tukang bakso yang lewat depan rumah.",
    textEn: "Dieting is easy; the hard part is resisting the street food vendor passing by the house.",
    author: "Pejuang Diet",
    category: "Relate",
  ),
  Quote(
    text: "Dompetku seperti bawang. Kalau dibuka, bawaannya pengen nangis.",
    textEn: "My wallet is like an onion. Whenever I open it, it makes me want to cry.",
    author: "Sobat Hemat",
    category: "Relate",
  ),
  Quote(
    text: "Rencana bangun pagi: Jam 4 Subuh. Realita bangun pagi: Jam 4 Subuh (tapi di mimpi).",
    textEn: "Plan: Wake up at 4 AM. Reality: Woke up at 4 AM (but only in my dreams).",
    author: "Netizen",
    category: "Relate",
  ),
  Quote(
    text: "Saldo ATM adalah mood booster terbaik, mengalahkan kata-kata motivasi manapun.",
    textEn: "Bank balance is the best mood booster, beating any motivational quote ever written.",
    author: "Realistis",
    category: "Relate",
  ),
  Quote(
    text: "Pura-pura sibuk di tempat kerja biar kelihatan produktif saat bos lewat adalah skill survival.",
    textEn: "Pretending to be busy when the boss walks by is a top-tier survival skill.",
    author: "Karyawan Teladan",
    category: "Relate",
  ),
  Quote(
    text: "Teman sejati itu bukan yang selalu ada, tapi yang kalau pinjam duit tahu diri buat balikin.",
    textEn: "A true friend isn't just someone who's always there, but someone who actually pays back the money they borrowed.",
    author: "Korban Teman",
    category: "Relate",
  ),
  Quote(
    text: "Niat hati cuma mau lihat jam di HP, eh malah kebablasan scroll media sosial 2 jam.",
    textEn: "Intended to just check the time on my phone, ended up scrolling social media for 2 hours.",
    author: "Netizen",
    category: "Relate",
  ),
  Quote(
    text: "Olahraga 15 menit, foto selfie dan update statusnya 30 menit, istirahatnya 3 hari.",
    textEn: "Work out for 15 minutes, take selfies and post for 30 minutes, rest for 3 days.",
    author: "Atlet Sosmed",
    category: "Relate",
  ),
  Quote(
    text: "Keranjang belanja online penuh impian, tapi saldo rekening penuh cobaan.",
    textEn: "Online shopping cart full of dreams, bank account balance full of struggles.",
    author: "Sobat Checkout",
    category: "Relate",
  ),
  Quote(
    text: "Lupa password itu seni. Giliran mau reset, dibilang 'Password tidak boleh sama dengan yang lama'.",
    textEn: "Forgetting passwords is an art. When you try to reset, it says 'New password cannot be the same as the old one'.",
    author: "Manusia Modern",
    category: "Relate",
  ),
  Quote(
    text: "Bilangnya 'OTW' (On The Way), padahal aslinya 'OTW' (Okelah Tunggu Wae, baru mau mandi).",
    textEn: "Saying 'OTW' (On the way), when it actually means 'Okay, just wait' (I'm just getting in the shower).",
    author: "Jam Karet",
    category: "Relate",
  ),
  Quote(
    text: "Bahagia itu sederhana: Wifi kencang, baterai penuh, dan cemilan ada di sebelah tangan.",
    textEn: "Happiness is simple: Fast Wifi, full battery, and snacks within reach.",
    author: "Netizen",
    category: "Relate",
  ),
  Quote(
    text: "Kadang aku merasa pintar, sampai akhirnya aku nyari kacamata yang ternyata sedang aku pakai.",
    textEn: "Sometimes I feel smart, until I start looking for the glasses I'm already wearing.",
    author: "Si Pelupa",
    category: "Relate",
  ),
  Quote(
    text: "Masuk toko barang branded, lihat label harga, lalu meletakkannya kembali dengan sangat hati-hati seolah itu bom.",
    textEn: "Entering a branded store, seeing the price tag, then putting it back as carefully as if it were a bomb.",
    author: "Sobat Irit",
    category: "Relate",
  ),
  Quote(
    text: "Gaji itu kayak menstruasi. Datangnya sebulan sekali, tahannya cuma seminggu.",
    textEn: "Salary is like a period. Comes once a month, lasts only about a week.",
    author: "Pekerja Keras",
    category: "Relate",
  ),
  Quote(
    text: "Punya baju sekabari, tapi tiap mau pergi bilangnya 'Gak punya baju'.",
    textEn: "Having a closet full of clothes, but saying 'I have nothing to wear' every time I go out.",
    author: "Netizen",
    category: "Relate",
  ),
  Quote(
    text: "Overthinking di malam hari adalah hobi yang tidak dibayar tapi rajin dilakukan.",
    textEn: "Nighttime overthinking is an unpaid hobby I practice very diligently.",
    author: "Insomnia Club",
    category: "Relate",
  ),
  Quote(
    text: "Google Maps bilang belok kanan, feeling bilang lurus. Akhirnya nyasar dan memaki Google Maps.",
    textEn: "Google Maps says turn right, my gut says straight. Ended up lost and swearing at Google Maps.",
    author: "Petualang Nyasar",
    category: "Relate",
  ),
  Quote(
    text: "Di grup WhatsApp ramai banget, pas diajak ketemuan alasannya sibuk menata masa depan.",
    textEn: "Active in the WhatsApp group, but when invited to meet, suddenly 'busy building the future'.",
    author: "Panitia Reuni",
    category: "Relate",
  ),
  Quote(
    text: "Definisi horor bagi orang dewasa: Ada panggilan tak terjawab dari Bos di hari libur.",
    textEn: "Definition of horror for adults: A missed call from the boss on a day off.",
    author: "Netizen",
    category: "Relate",
  ),
  Quote(
    text: "Hidup itu seperti roda berputar. Kadang di atas, kadang di bawah, kadang rodanya kempes.",
    textEn: "Life is like a wheel. Sometimes you're on top, sometimes you're at the bottom, sometimes the tire is flat.",
    author: "Filsuf Jalanan",
    category: "Relate",
  ),
  Quote(
    text: "Janji mau nabung, eh ada diskon 50%. Maafkan aku masa depan, diskon ini godaan terberat.",
    textEn: "Promised to save money, then saw a 50% discount. Sorry future self, the sale was too strong.",
    author: "Pemburu Diskon",
    category: "Relate",
  ),
  Quote(
    text: "Mandi adalah kegiatan opsional jika hari itu tidak ada rencana keluar rumah.",
    textEn: "Showering is an optional activity if there are no plans to leave the house.",
    author: "Kaum Mager",
    category: "Relate",
  ),
  Quote(
    text: "Berhenti berharap pada manusia, karena mereka sering lupa balas chat padahal lagi online.",
    textEn: "Stop hoping in humans; they often forget to reply to your texts even when they're online.",
    author: "Netizen Galau",
    category: "Relate",
  ),
  Quote(
    text: "Kalau ada masalah, hadapilah dengan senyuman. Kalau masalahnya duit, senyum saja tidak cukup.",
    textEn: "Face every problem with a smile. If the problem is money, a smile isn't enough.",
    author: "Realita Hidup",
    category: "Relate",
  ),
  Quote(
    text: "Typo satu huruf bisa merubah makna, merusak suasana, dan memancing keributan.",
    textEn: "A single-letter typo can change the meaning, ruin the mood, and start a war.",
    author: "Jari Jempol",
    category: "Relate",
  ),
  Quote(
    text: "Mikirin caption Instagram 1 jam, yang nge-like cuma 5 orang. Itu pun keluarga sendiri.",
    textEn: "Spent an hour thinking of an Instagram caption, only got 5 likes�and those were from family.",
    author: "Selebgram Gagal",
    category: "Relate",
  ),
  Quote(
    text: "Penyakit anak muda zaman now: Lambung tak aman, punggung tak nyaman, dompet tak mapan.",
    textEn: "Modern youth problems: Acid reflux, back pain, and a broke wallet.",
    author: "Generasi Jompo",
    category: "Relate",
  ),
  Quote(
    text: "Niat hati mau 'Healing' (jalan-jalan), pulang-pulang malah 'Hilang' (uangnya).",
    textEn: "Intended to go 'Healing' (traveling), came home and realized my money was the one that 'Healed' away.",
    author: "Traveller Kere",
    category: "Relate",
  ),
  Quote(
    text: "Sabar itu ada batasnya, kalau nggak ada batasnya namanya sabar-sabar aja dibohongin.",
    textEn: "Patience has limits. If it doesn't, it's just called 'being okay with being lied to'.",
    author: "Netizen",
    category: "Relate",
  ),
  Quote(
    text: "Perbedaan teori dan praktik: Teori itu tahu caranya tapi gak jalan. Praktik itu jalan tapi gak tahu caranya.",
    textEn: "Difference between theory and practice: Theory is knowing how but not working. Practice is working but not knowing how.",
    author: "Mahasiswa Abadi",
    category: "Relate",
  ),
  Quote(
    text: "Pulpen di kantor itu kakinya banyak. Baru ditaruh sebentar, sudah jalan-jalan entah ke meja siapa.",
    textEn: "Office pens have many legs. You put one down for a second, and it wanders off to someone else's desk.",
    author: "Admin Kantor",
    category: "Relate",
  ),
  Quote(
    text: "Tanya 'Mau makan apa?' jawabnya 'Terserah'. Giliran dibeliin, bilangnya 'Kok ini sih?'.",
    textEn: "Asking 'What do you want to eat?' and getting 'Whatever'. Then buying it and hearing 'Why this?'.",
    author: "Korban Terserah",
    category: "Relate",
  ),
  Quote(
    text: "Menyelesaikan masalah dengan tidur. Pas bangun, masalahnya masih ada, tapi setidaknya sudah nggak ngantuk.",
    textEn: "Solving problems by sleeping. When I wake up, the problems are still there, but at least I'm not sleepy anymore.",
    author: "Solusi Instan",
    category: "Relate",
  ),
  Quote(
    text: "Screenshot chat adalah asuransi digital. Disimpan buat bukti kalau suatu hari ada drama.",
    textEn: "Chat screenshots are digital insurance. Saved as evidence for future drama.",
    author: "Arsiparis Digital",
    category: "Relate",
  ),
  Quote(
    text: "Uang receh kalau jatuh di jalan suaranya nyaring. Giliran uang kertas jatuh, hening tak terdengar.",
    textEn: "Coins make a loud sound when they fall. Bills, on the other hand, fall in total silence.",
    author: "Hukum Alam",
    category: "Relate",
  ),
  Quote(
    text: "Filter kamera jahat banget. Di layar glowing, di cermin bikin overthinking.",
    textEn: "Camera filters are evil. Glowing on screen, but making me overthink in front of the mirror.",
    author: "Korban Filter",
    category: "Relate",
  ),
  Quote(
    text: "Hari Senin itu tidak salah, yang salah itu kenapa liburnya cuma hari Minggu.",
    textEn: "Monday isn't the problem; the problem is why Sunday is the only day off.",
    author: "Musuh Senin",
    category: "Relate",
  ),
  Quote(
    text: "Setrikaan itu kayak gunung berapi. Kalau didiemin numpuk, kalau dikerjain panas.",
    textEn: "Ironing is like a volcano. If you leave it, it piles up; if you do it, it's hot.",
    author: "Ibu Rumah Tangga",
    category: "Relate",
  ),
  Quote(
    text: "Lagi sholat khusyuk banget, tiba-tiba ingat kunci motor yang hilang seharian ternyata ada di saku celana.",
    textEn: "Praying very solemnly, then suddenly remembering the missing keys have been in my pocket all day.",
    author: "Hamba Allah",
    category: "Relate",
  ),
  Quote(
    text: "Nabung rindu itu berat, mending nabung duit biar bisa halalin kamu.",
    textEn: "Saving up longing is hard; better save up money so I can marry you.",
    author: "Pejuang Mahar",
    category: "Relate",
  ),
  Quote(
    text: "Charger HP dipinjam teman itu rasanya kayak melepas anak gadis pergi merantau. Was-was gak balik.",
    textEn: "Lending your charger to a friend feels like letting your daughter move away. You're anxious it won't return.",
    author: "Posesif Gadget",
    category: "Relate",
  ),
  Quote(
    text: "Ketawa 'WKWKWK' di chat, padahal mukanya datar sedatar aspal jalan tol.",
    textEn: "Typing 'HAHAHA' in chat, while my face is as flat as a highway.",
    author: "Muka Datar",
    category: "Relate",
  ),
  Quote(
    text: "Hujan itu 1% air, 99% kenangan. Eh salah, 99% bikin mager dan pengen mie instan.",
    textEn: "Rain is 1% water and 99% memories. Actually, it's 99% wanting to stay in bed and eat instant noodles.",
    author: "Anak Senja",
    category: "Relate",
  ),
  Quote(
    text: "Salah sapa orang di jalan itu malunya bisa sampai 7 turunan, apalagi kalau udah teriak woy.",
    textEn: "Waving at the wrong person on the street is a shame that lasts seven generations, especially if you shouted.",
    author: "Si Rabun",
    category: "Relate",
  ),
  Quote(
    text: "Kerjaan numpuk, deadline mepet, tapi motivasi malah tiarap.",
    textEn: "Work is piling up, deadline is near, but my motivation is currently playing hide and seek.",
    author: "Deadliners",
    category: "Relate",
  ),
  Quote(
    text: "Semakin dewasa, lingkaran pertemanan semakin kecil. Sisanya cuma penonton story.",
    textEn: "As we get older, our friend circle gets smaller. The rest are just story viewers.",
    author: "Introvert",
    category: "Relate",
  ),
  Quote(
    text: "Udah niat banget mau marah, pas lihat mukanya yang melas malah jadi ketawa. Gagal garang.",
    textEn: "I intended to be angry, but seeing their pathetic face made me laugh. Failed to be tough.",
    author: "Hati Hello Kitty",
    category: "Relate",
  ),
  Quote(
    text: "Hidup itu simpel. Lapar makan, ngantuk tidur, gak punya duit kerja. Jangan dibikin ribet.",
    textEn: "Life is simple. Hungry? Eat. Sleepy? Sleep. Broke? Work. Don't make it complicated.",
    author: "Cak Lontong KW",
    category: "Relate",
  ),
  Quote(
    text: "Masak ngikutin tutorial YouTube. Ekspektasi: Chef Profesional. Realita: Chef Gosong.",
    textEn: "Cooking via YouTube tutorial. Expectation: Professional Chef. Reality: Burnt everything.",
    author: "Koki Dadakan",
    category: "Relate",
  ),
  Quote(
    text: "Fakir kuota: Tahu password wifi masjid atau kafe lebih penting daripada tahu menu makanannya.",
    textEn: "Data-broke: Knowing the WiFi password is more important than knowing the food menu.",
    author: "Pemburu Wifi",
    category: "Relate",
  ),
  Quote(
    text: "Musuh terbesar anak kos: Hujan turun deras saat jemuran baru setengah kering.",
    textEn: "The biggest enemy of a student: Heavy rain when the laundry is only half-dry.",
    author: "Anak Rantau",
    category: "Relate",
  ),
  Quote(
    text: "Sabtu Minggu itu durasinya kayak trailer film, Senin sampai Jumat durasinya kayak film India.",
    textEn: "Weekends feel like movie trailers; Monday to Friday feels like a 3-hour movie.",
    author: "Netizen",
    category: "Relate",
  ),
  Quote(
    text: "Tertawa paling palsu adalah saat bos bikin lelucon garing tapi kita butuh THR cair lancar.",
    textEn: "The fakest laugh is when your boss tells a dry joke but you really need that holiday bonus.",
    author: "Budak Korporat",
    category: "Relate",
  ),
  Quote(
    text: "Otak di siang hari: *Loading...*. Otak pas mau tidur: 'Ingat kejadian memalukan 5 tahun lalu?'.",
    textEn: "Brain during the day: *Loading...*. Brain at bedtime: 'Remember that embarrassing thing 5 years ago?'.",
    author: "Overthinker",
    category: "Relate",
  ),
  Quote(
    text: "Masuk kamar, diam sebentar, lalu keluar lagi karena lupa mau ngapain. Efek penuaan dini?",
    textEn: "Walking into a room, standing still, then leaving because I forgot why I went in there.",
    author: "Si Pikun",
    category: "Relate",
  ),
  Quote(
    text: "Di grup WA cuma jadi 'silent reader', giliran ada info giveaway paling cepat muncul.",
    textEn: "A silent reader in the group chat, until there's a giveaway�then I'm the fastest.",
    author: "CCTV Grup",
    category: "Relate",
  ),
  Quote(
    text: "Menghilangkan Tupperware ibu lebih menakutkan risikonya daripada diputusin pacar.",
    textEn: "Losing your mom's Tupperware is more dangerous than getting dumped by your partner.",
    author: "Anak Durhaka",
    category: "Relate",
  ),
  Quote(
    text: "Buka kulkas, bengong, tutup lagi. Ulangi 10 menit kemudian berharap isinya berubah jadi restoran.",
    textEn: "Opening the fridge, staring, closing it. Repeating 10 minutes later hoping it turned into a restaurant.",
    author: "Si Lapar",
    category: "Relate",
  ),
  Quote(
    text: "Daftar member gym biar sehat (X). Daftar member gym biar jadi donatur tetap (V).",
    textEn: "Joining the gym to get fit (X). Joining the gym to be a permanent monthly donor (V).",
    author: "Niat Doang",
    category: "Relate",
  ),
  Quote(
    text: "Mulut: 'Pedasnya nendang!'. Perut: 'Tolong, aku gak kuat!'. Besoknya tetap beli lagi.",
    textEn: "Mouth: 'This spice is great!'. Stomach: 'Please, have mercy!'. Buying it again the next day.",
    author: "Pecinta Seblak",
    category: "Relate",
  ),
  Quote(
    text: "Nyolok USB itu hukumnya wajib 3 kali coba. Atas salah, balik bawah salah, balik atas lagi baru masuk.",
    textEn: "Plugging in a USB requires 3 tries. Wrong side, flip it�wrong side, flip it back�fits.",
    author: "Misteri IT",
    category: "Relate",
  ),
  Quote(
    text: "Saat kurir teriak 'Paket!', jantung berdebar lebih kencang daripada saat ditembak gebetan.",
    textEn: "When the courier shouts 'Package!', my heart beats faster than when my crush texts me.",
    author: "Sobat Belanja",
    category: "Relate",
  ),
  Quote(
    text: "Bilang ke tukang cukur 'potong dikit aja', keluarnya malah kayak mau berangkat wajib militer.",
    textEn: "Telling the barber 'just a trim', walking out looking like I'm joining the army.",
    author: "Korban Barbershop",
    category: "Relate",
  ),
  Quote(
    text: "Musim nikah: Dompet menipis, stok baju kondangan menipis, pertanyaan 'kapan nyusul' menebal.",
    textEn: "Wedding season: Thin wallet, limited formal wear, thick questions about when I'm next.",
    author: "Jomblo Fisabilillah",
    category: "Relate",
  ),
  Quote(
    text: "Baru pakai jas hujan ribet-ribet, eh hujannya berhenti. Alam semesta sedang bercanda.",
    textEn: "Just finished struggling into my raincoat, and the rain stopped. The universe is trolling me.",
    author: "Pengendara Motor",
    category: "Relate",
  ),
  Quote(
    text: "Niat makeup 'No Makeup Look', hasilnya malah kayak ondel-ondel mau pentas.",
    textEn: "Tried the 'No Makeup Look', ended up looking like a circus clown.",
    author: "Beauty Vlogger Gagal",
    category: "Relate",
  ),
  Quote(
    text: "Bawa powerbank berat-berat buat jaga-jaga, pas mau dipakai ternyata powerbank-nya lupa dicharge.",
    textEn: "Carrying a heavy power bank just in case, only to find out I forgot to charge the power bank.",
    author: "Manusia Apes",
    category: "Relate",
  ),
  Quote(
    text: "Pakai headset bukan buat denger lagu, tapi biar gak diajak ngobrol orang sebelah di angkot.",
    textEn: "Wearing headphones not to listen to music, but to avoid small talk with strangers.",
    author: "Introvert Cerdas",
    category: "Relate",
  ),
  Quote(
    text: "Perang stiker di WhatsApp lebih seru dan emosional daripada debat kusir di TV.",
    textEn: "Sticker wars on WhatsApp are more intense than political debates on TV.",
    author: "Netizen",
    category: "Relate",
  ),
  Quote(
    text: "Galeri HP isinya: 10% foto diri, 90% screenshot chat dan meme yang gak tahu kapan gunanya.",
    textEn: "Phone gallery: 10% selfies, 90% memes and screenshots I'll probably never use.",
    author: "Penimbun Digital",
    category: "Relate",
  ),
  Quote(
    text: "Niat tidur jam 10 malam. Realitanya jam 2 pagi masih nonton video kucing di internet.",
    textEn: "Planned to sleep at 10 PM. Reality: 2 AM and still watching cat videos.",
    author: "Insomnia Akut",
    category: "Relate",
  ),
  Quote(
    text: "Uang tidak bisa membeli kebahagiaan, tapi nangis di dalam mobil mewah lebih nyaman daripada di sepeda.",
    textEn: "Money can't buy happiness, but crying in a luxury car is more comfortable than on a bicycle.",
    author: "Matre Realistis",
    category: "Relate",
  ),
  Quote(
    text: "Kalimat 'Diet mulai besok' adalah kebohongan publik yang paling sering diucapkan pada diri sendiri.",
    textEn: "'Diet starts tomorrow' is the biggest lie we tell ourselves.",
    author: "Hobi Makan",
    category: "Relate",
  ),
  Quote(
    text: "Bekerjalah sampai tetangga mengira kamu pelihara tuyul karena jarang keluar rumah.",
    textEn: "Work until your neighbors think you're up to something shady because you never leave the house.",
    author: "Freelancer",
    category: "Relate",
  ),
  Quote(
    text: "Minum kopi biar melek (X). Minum kopi biar jantung deg-degan dan asam lambung naik (V).",
    textEn: "Drinking coffee to wake up (X). Drinking coffee to get heart palpitations and acid reflux (V).",
    author: "Sobat Kafein",
    category: "Relate",
  ),
  Quote(
    text: "Nyari barang gak ketemu-ketemu. Pas ibu yang nyari, langsung ketemu dalam 5 detik. Magic.",
    textEn: "Searching for something for an hour. Mom finds it in 5 seconds. Magic.",
    author: "Anak Mama",
    category: "Relate",
  ),
  Quote(
    text: "Ditelepon nomor tak dikenal: Angkat gak ya? Jangan-jangan penipuan. Atau kurir paket? Galau.",
    textEn: "Call from an unknown number: Should I pick up? Scam? Or my package? The anxiety is real.",
    author: "Introvert",
    category: "Relate",
  ),
  Quote(
    text: "Payung itu benda gaib. Pas hujan hilang entah kemana, pas panas ada di mana-mana.",
    textEn: "Umbrellas are mystical objects. They vanish when it rains and appear everywhere when it's sunny.",
    author: "Korban Hujan",
    category: "Relate",
  ),
  Quote(
    text: "Kakak adik itu akur cuma pas lagi ada maunya atau lagi sekongkol bohongin orang tua.",
    textEn: "Siblings only get along when they want something or are conspiring to lie to their parents.",
    author: "Sibling Goals",
    category: "Relate",
  ),
  Quote(
    text: "Antrian sebelah selalu lebih cepat jalannya daripada antrian kita. Hukum alam yang menyebalkan.",
    textEn: "The other line always moves faster. It's an annoying law of nature.",
    author: "Pengantri Sejati",
    category: "Relate",
  ),
  Quote(
    text: "Botol sampo habis diisi air kocok-kocok sampai busanya hilang. Tanda kearifan lokal.",
    textEn: "Putting water in an empty shampoo bottle and shaking it. Peak frugality.",
    author: "Tips Hemat",
    category: "Relate",
  ),
  Quote(
    text: "Lupa bawa handuk pas selesai mandi. Teriak panggil orang rumah adalah momen uji vokal.",
    textEn: "Forgetting the towel after a shower. Shouting for help is a true vocal test.",
    author: "Penyanyi Kamar Mandi",
    category: "Relate",
  ),
  Quote(
    text: "Nyamuk yang bunyi 'ngiiing' di kuping itu lebih ngeselin mental daripada nyamuk yang gigit diam-diam.",
    textEn: "Mosquitoes buzzing in your ear is more mentally draining than them actually biting you.",
    author: "Musuh Nyamuk",
    category: "Relate",
  ),
  Quote(
    text: "Bikin password rumit biar aman, akhirnya malah lupa sendiri dan harus klik 'Lupa Password'.",
    textEn: "Created a complex password for security, then forgot it and had to reset immediately.",
    author: "Netizen",
    category: "Relate",
  ),
  Quote(
    text: "Ekspektasi liburan: Foto estetik. Realita: Foto burem, antri panjang, tempat wisata lautan manusia.",
    textEn: "Vacation expectation: Aesthetic photos. Reality: Blurry pics, long lines, and crowds everywhere.",
    author: "Turis Lokal",
    category: "Relate",
  ),
  Quote(
    text: "Baterai sosial habis. Mohon jangan ajak bicara, cukup kirim makanan dan transferan.",
    textEn: "Social battery is drained. Don't talk to me; just send food and money.",
    author: "Introvert Lelah",
    category: "Relate",
  ),
  Quote(
    text: "Tumpukan baju di kursi kamar kadang terlihat seperti monster saat lampu dimatikan.",
    textEn: "The pile of clothes on the chair looks like a monster once the lights go out.",
    author: "Penakut",
    category: "Relate",
  ),
  Quote(
    text: "Nonton Drama Korea maraton sampai pagi kuat, baca buku pelajaran 5 menit langsung ngantuk.",
    textEn: "Binging K-Dramas until sunrise? Easy. Reading a textbook for 5 minutes? Instant sleep.",
    author: "Pelajar",
    category: "Relate",
  ),
  Quote(
    text: "Kabel earphone di saku bisa mengikat dirinya sendiri dengan simpul mati. Bakat terpendam.",
    textEn: "Wired earphones can tie themselves into impossible knots inside a pocket. Truly a hidden talent.",
    author: "Misteri Fisika",
    category: "Relate",
  ),
  Quote(
    text: "Balas chat lama banget, alasannya 'ketiduran'. Padahal ketiduran selama 3 hari.",
    textEn: "Took forever to reply because I 'fell asleep'. Fell asleep for 3 days, apparently.",
    author: "Tukang Ghosting",
    category: "Relate",
  ),
  Quote(
    text: "Menambahkan barang ke keranjang itu terapi jiwa, membayarnya itu trauma dompet.",
    textEn: "Adding items to the cart is therapy; paying for them is trauma.",
    author: "Sobat Checkout",
    category: "Relate",
  ),
  Quote(
    text: "Pasang alarm jam 5, 5:05, 5:10, 5:15. Bangunnya jam 7 pas semua alarm sudah nyerah.",
    textEn: "Setting alarms for 5, 5:05, 5:10, 5:15. Woke up at 7 once the alarms gave up.",
    author: "Pejuang Subuh",
    category: "Relate",
  ),
  Quote(
    text: "Tanya harga di komentar 'Cek DM Kak'. Kenapa harga aja harus jadi rahasia negara?",
    textEn: "Asking for the price and getting 'Check DM'. Why is the price a state secret?",
    author: "Pembeli Bingung",
    category: "Relate",
  ),
  Quote(
    text: "Zoom meeting: Atasan suruh on cam, aku panik cari kerudung instan dan lipstik.",
    textEn: "Zoom meeting: Boss says turn on camera, I panic looking for a quick outfit and lipstick.",
    author: "Warga WFH",
    category: "Relate",
  ),
  Quote(
    text: "Beli buku banyak biar kelihatan pintar (Tsundoku), bacanya tetap status Whatsapp orang.",
    textEn: "Buying books to look smart (Tsundoku), but only reading people's WhatsApp statuses.",
    author: "Kolektor Buku",
    category: "Relate",
  ),
  Quote(
    text: "Sinyal HP itu kayak jodoh. Dicari susah, giliran gak diharapkan malah muncul '4G Full Bar'.",
    textEn: "Phone signal is like a soulmate. Hard to find, but appears when you least expect it.",
    author: "Fakir Sinyal",
    category: "Relate",
  ),
];