import '../models_daily_free/quote_model.dart';

List<Quote> selfLoveQuotes = [
  Quote(
    text: "Mencintai diri sendiri bukanlah kesombongan, melainkan kebutuhan agar kamu tetap waras di dunia yang gila ini.",
    textEn: "Loving yourself is not vanity, but a necessity to stay sane in this crazy world.",
    author: "Anonim",
    category: "Self Love",
  ),
  Quote(
    text: "Kamu tidak perlu menjadi sempurna untuk menjadi layak dicintai. Cukup menjadi dirimu sendiri.",
    textEn: "You don't need to be perfect to be worthy of love. Being yourself is enough.",
    author: "Anonim",
    category: "Self Love",
  ),
  Quote(
    text: "Beristirahatlah, dunia tidak akan runtuh hanya karena kamu mengambil jeda sejenak.",
    textEn: "Take a rest; the world will not crumble just because you took a short pause.",
    author: "Unknown",
    category: "Self Love",
  ),
  Quote(
    text: "Memaafkan diri sendiri adalah langkah pertama untuk menyembuhkan luka yang tak terlihat.",
    textEn: "Forgiving yourself is the first step to healing invisible wounds.",
    author: "Anonim",
    category: "Self Love",
  ),
  Quote(
    text: "Standar kecantikanmu tidak ditentukan oleh 'like' di media sosial, tapi oleh bagaimana kamu mensyukuri ciptaan Tuhan.",
    textEn: "Your beauty standard is not determined by 'likes' on social media, but by how you cherish God's creation.",
    author: "Anonim",
    category: "Self Love",
  ),
  Quote(
    text: "Menetapkan batasan (boundaries) bukan berarti jahat, itu cara menjaga kewarasan agar tetap bisa berbuat baik.",
    textEn: "Setting boundaries isn't being mean; it's a way to protect your sanity to keep doing good.",
    author: "Morgan Harper Nichols",
    category: "Self Love",
  ),
  Quote(
    text: "Kamu tidak terlambat, kamu tidak tertinggal. Kamu sedang berjalan di zona waktumu sendiri.",
    textEn: "You are not late, you are not behind. You are walking in your own time zone.",
    author: "Anonim",
    category: "Self Love",
  ),
  Quote(
    text: "Tumbuh itu tidak harus langsung besar. Tunas kecil yang bertahan badai pun adalah sebuah kemajuan.",
    textEn: "Growth doesn't have to be massive all at once. A tiny bud surviving the storm is also progress.",
    author: "Anonim",
    category: "Self Love",
  ),
  Quote(
    text: "Berhenti membandingkan proses di balik layarmu dengan sorotan terbaik (highlight) orang lain.",
    textEn: "Stop comparing your behind-the-scenes with everyone else's highlight reel.",
    author: "Steven Furtick",
    category: "Self Love",
  ),
  Quote(
    text: "Menjadi lembut pada diri sendiri di hari-hari yang berat adalah bentuk ibadah hati.",
    textEn: "Being gentle with yourself on hard days is a form of spiritual worship.",
    author: "Anonim",
    category: "Self Love",
  ),
  Quote(
    text: "Perasaanmu valid. Jangan mengecilkan badai di dadamu hanya karena orang lain tidak basah kuyup.",
    textEn: "Your feelings are valid. Don't downplay the storm in your chest just because others aren't getting wet.",
    author: "Unknown",
    category: "Self Love",
  ),
  Quote(
    text: "Investasi terbaik yang bisa kamu lakukan adalah berinvestasi pada kesehatan mental dan spiritualmu sendiri.",
    textEn: "The best investment you can make is in your own mental and spiritual health.",
    author: "Anonim",
    category: "Self Love",
  ),
  Quote(
    text: "Kamu tidak bisa menuangkan air dari gelas yang kosong. Cintai dirimu dulu sebelum memberi pada yang lain.",
    textEn: "You cannot pour from an empty cup. Love yourself first before giving to others.",
    author: "Eleanor Brown",
    category: "Self Love",
  ),
  Quote(
    text: "Salah satu bentuk rasa syukur tertinggi adalah menerima dirimu apa adanya, lengkap dengan segala ketidaksempurnaannya.",
    textEn: "One of the highest forms of gratitude is accepting yourself as you are, complete with all your imperfections.",
    author: "Anonim",
    category: "Self Love",
  ),
  Quote(
    text: "Menjauh dari hal-hal yang merusak ketenangan batinmu bukanlah egois, itu perlindungan diri.",
    textEn: "Distance yourself from things that destroy your inner peace; it's not selfish, it's self-protection.",
    author: "Unknown",
    category: "Self Love",
  ),
  Quote(
    text: "Jangan bakar dirimu hanya untuk menghangatkan orang lain yang bahkan tidak peduli.",
    textEn: "Don't set yourself on fire just to keep others warm when they don't even care.",
    author: "Penny Reid",
    category: "Self Love",
  ),
  Quote(
    text: "Tubuhmu adalah amanah, rawatlah ia bukan karena benci melihat cermin, tapi karena syukur ia telah menemanimu sejauh ini.",
    textEn: "Your body is a trust; care for it not because you hate the mirror, but because you're grateful it has carried you this far.",
    author: "Anonim",
    category: "Self Love",
  ),
  Quote(
    text: "Keberhargaanmu tidak berkurang sedikitpun hanya karena seseorang tidak mampu melihat nilainya.",
    textEn: "Your worth does not decrease just because someone is unable to see its value.",
    author: "Unknown",
    category: "Self Love",
  ),
  Quote(
    text: "Bunga tidak berpikir untuk bersaing dengan bunga di sebelahnya. Ia hanya mekar.",
    textEn: "A flower does not think of competing with the flower next to it. It just blooms.",
    author: "Zen Shin",
    category: "Self Love",
  ),
  Quote(
    text: "Terkadang 'healing' terbaik hanyalah diam, sujud, dan menyadari bahwa kamu tidak sendirian.",
    textEn: "Sometimes the best 'healing' is simply silence, prostration, and realizing you are not alone.",
    author: "Anonim",
    category: "Self Love",
  ),
  Quote(
    text: "Katakan 'tidak' tanpa rasa bersalah. Itu adalah kalimat utuh yang menyelamatkan energimu.",
    textEn: "Say 'no' without guilt. It is a complete sentence that saves your energy.",
    author: "Unknown",
    category: "Self Love",
  ),
  Quote(
    text: "Progres itu tidak selalu naik. Kadang diam dan bertahan hidup hari ini pun adalah sebuah progres.",
    textEn: "Progress isn't always upward. Sometimes staying quiet and surviving the day is progress too.",
    author: "Anonim",
    category: "Self Love",
  ),
  Quote(
    text: "Kamu diizinkan untuk menjadi karya seni yang belum selesai (work in progress) dan tetap menjadi mahakarya.",
    textEn: "You are allowed to be a work in progress and still be a masterpiece.",
    author: "Sophia Bush",
    category: "Self Love",
  ),
  Quote(
    text: "Mencintai diri sendiri adalah awal dari romansa seumur hidup.",
    textEn: "To love oneself is the beginning of a lifelong romance.",
    author: "Oscar Wilde",
    category: "Self Love",
  ),
  Quote(
    text: "Jangan biarkan komentar orang asing menyewa ruang di kepalamu secara gratis.",
    textEn: "Don't let strangers' comments rent space in your head for free.",
    author: "Unknown",
    category: "Self Love",
  ),
  Quote(
    text: "Merayakan kemenangan kecil itu penting. Bangun pagi dan tidak menyerah pun layak dirayakan.",
    textEn: "Celebrating small wins matters. Waking up and not giving up is worth celebrating.",
    author: "Anonim",
    category: "Self Love",
  ),
  Quote(
    text: "Luka batinmu mungkin bukan salahmu, tapi kesembuhannya adalah tanggung jawabmu.",
    textEn: "Your inner wounds might not be your fault, but healing them is your responsibility.",
    author: "Marianne Williamson",
    category: "Self Love",
  ),
  Quote(
    text: "Kamu adalah pemeran utama di hidupmu. Berhentilah mencoba menjadi pemeran pembantu di hidup orang lain.",
    textEn: "You are the lead character in your life. Stop trying to be a supporting character in someone else's.",
    author: "Anonim",
    category: "Self Love",
  ),
  Quote(
    text: "Bicaralah pada dirimu sendiri seperti kamu berbicara pada seseorang yang sangat kamu cintai.",
    textEn: "Talk to yourself like you would to someone you love dearly.",
    author: "Brene Brown",
    category: "Self Love",
  ),
  Quote(
    text: "Kesepian itu mahal, tapi berada dalam hubungan yang membuatmu merasa sendirian itu jauh lebih mahal.",
    textEn: "Loneliness is expensive, but being in a relationship that makes you feel alone is far more costly.",
    author: "Unknown",
    category: "Self Love",
  ),
  Quote(
    text: "Menangis bukan tanda lemah. Awan pun butuh hujan agar langit kembali cerah.",
    textEn: "Crying is not a sign of weakness. Even clouds need rain for the sky to clear again.",
    author: "Anonim",
    category: "Self Love",
  ),
  Quote(
    text: "Kamu cukup. Kamu sudah cukup sejak detik pertama kamu diciptakan.",
    textEn: "You are enough. You have been enough since the first second you were created.",
    author: "Maya Angelou",
    category: "Self Love",
  ),
  Quote(
    text: "Jangan menunggu kurus, jangan menunggu kaya, jangan menunggu sukses untuk mulai menyayangi dirimu.",
    textEn: "Don't wait to be thin, rich, or successful to start loving yourself.",
    author: "Anonim",
    category: "Self Love",
  ),
  Quote(
    text: "Validasi terpenting datang dari cermin, bukan dari layar handphone.",
    textEn: "The most important validation comes from the mirror, not from a phone screen.",
    author: "Unknown",
    category: "Self Love",
  ),
  Quote(
    text: "Tugasmu bukan menjadi disukai semua orang. Tugasmu adalah menjadi dirimu sendiri dan menemukan orang yang tepat.",
    textEn: "Your job is not to be liked by everyone. Your job is to be yourself and find the right people.",
    author: "Anonim",
    category: "Self Love",
  ),
  Quote(
    text: "Lepaskan ekspektasi untuk menjadi sempurna. Jadilah nyata, itu jauh lebih berharga.",
    textEn: "Let go of the expectation to be perfect. Be real; that is far more valuable.",
    author: "Unknown",
    category: "Self Love",
  ),
  Quote(
    text: "Hati yang damai adalah balas dendam terbaik terhadap kebisingan dunia.",
    textEn: "A peaceful heart is the best revenge against the world's noise.",
    author: "Anonim",
    category: "Self Love",
  ),
  Quote(
    text: "Tarik napas. Kamu sudah melalui banyak hal sulit sebelumnya, dan kamu akan melalui yang ini juga.",
    textEn: "Take a breath. You've been through many hard things before, and you'll get through this too.",
    author: "Unknown",
    category: "Self Love",
  ),
  Quote(
    text: "Mencintai diri sendiri berarti memberi izin pada hatimu untuk bahagia tanpa syarat.",
    textEn: "Self-love means giving your heart permission to be happy unconditionally.",
    author: "Anonim",
    category: "Self Love",
  ),
  Quote(
    text: "Jangan mengecilkan cahayamu hanya agar orang lain merasa nyaman dalam kegelapan mereka.",
    textEn: "Don't shrink your light just so others can feel comfortable in their darkness.",
    author: "Marianne Williamson",
    category: "Self Love",
  ),
  Quote(
    text: "Kebaikan yang kamu tanam untuk dirimu sendiri akan berbuah kebaikan bagi orang di sekitarmu.",
    textEn: "The kindness you plant for yourself will bear fruit for those around you.",
    author: "Unknown",
    category: "Self Love",
  ),
  Quote(
    text: "Sendiri tidak selalu berarti sepi. Itu bisa jadi waktu berkualitas antara kamu dan Sang Pencipta.",
    textEn: "Being alone doesn't always mean being lonely. It can be quality time between you and the Creator.",
    author: "Anonim",
    category: "Self Love",
  ),
  Quote(
    text: "Tidak apa-apa untuk memulai lagi dari awal. Kali ini kamu tidak mulai dari nol, tapi dari pengalaman.",
    textEn: "It's okay to start over. This time you're not starting from zero, but from experience.",
    author: "Unknown",
    category: "Self Love",
  ),
  Quote(
    text: "Menghindari drama bukan berarti antisosial, itu berarti kamu menghargai kedamaianmu.",
    textEn: "Avoiding drama isn't being antisocial; it means you value your peace.",
    author: "Anonim",
    category: "Self Love",
  ),
  Quote(
    text: "Kamu berhak mendapatkan cinta yang sama besarnya dengan cinta yang selalu kamu berikan kepada orang lain.",
    textEn: "You deserve a love as great as the one you've always given to others.",
    author: "Unknown",
    category: "Self Love",
  ),
  Quote(
    text: "Fokuslah pada langkah di depanmu, bukan pada seberapa tinggi gunung yang harus didaki.",
    textEn: "Focus on the step in front of you, not on how high the mountain is to climb.",
    author: "Anonim",
    category: "Self Love",
  ),
  Quote(
    text: "Menjadi autentik adalah bentuk keberanian tertinggi di dunia yang selalu memintamu menjadi orang lain.",
    textEn: "To be authentic is the highest form of courage in a world that asks you to be someone else.",
    author: "E.E. Cummings",
    category: "Self Love",
  ),
  Quote(
    text: "Rasa insecure-mu adalah ilusi. Potensimu adalah realita yang menunggu diasah.",
    textEn: "Your insecurity is an illusion. Your potential is a reality waiting to be honed.",
    author: "Unknown",
    category: "Self Love",
  ),
  Quote(
    text: "Hari buruk tidak mendefinisikan seluruh hidupmu. Itu hanya 24 jam yang perlu dilewati.",
    textEn: "A bad day doesn't define your whole life. It's just 24 hours that need to be passed.",
    author: "Anonim",
    category: "Self Love",
  ),
  Quote(
    text: "Maafkan dirimu yang dulu. Dia melakukan yang terbaik dengan pengetahuan yang dia miliki saat itu.",
    textEn: "Forgive your past self. They did the best they could with the knowledge they had at the time.",
    author: "Maya Angelou",
    category: "Self Love",
  ),
  Quote(
    text: "Kecantikan sejati dimulai saat kamu memutuskan untuk menjadi dirimu sendiri.",
    textEn: "Beauty begins the moment you decide to be yourself.",
    author: "Coco Chanel",
    category: "Self Love",
  ),
  Quote(
    text: "Jadilah prioritas dalam hidupmu sendiri, bukan sekadar pilihan cadangan.",
    textEn: "Be a priority in your own life, not just a backup option.",
    author: "Anonim",
    category: "Self Love",
  ),
  Quote(
    text: "Mencintai diri sendiri adalah revolusi diam-diam melawan dunia yang memaksamu menjadi orang lain.",
    textEn: "Self-love is a quiet revolution against a world that forces you to be someone else.",
    author: "Anonim",
    category: "Self Love",
  ),
  Quote(
    text: "Jangan biarkan masa lalu menyandera masa depanmu. Maafkan, lepaskan, dan melangkah.",
    textEn: "Don't let the past hijack your future. Forgive, release, and move forward.",
    author: "Unknown",
    category: "Self Love",
  ),
  Quote(
    text: "Rumput tetangga terlihat lebih hijau mungkin karena sering diberi filter. Fokuslah menyiram rumputmu sendiri.",
    textEn: "The neighbor's grass looks greener because it's probably filtered. Focus on watering your own grass.",
    author: "Anonim",
    category: "Self Love",
  ),
  Quote(
    text: "Kamu tidak didefinisikan oleh satu kesalahan. Kamu adalah kumpulan dari bagaimana kamu bangkit setelahnya.",
    textEn: "You are not defined by a single mistake. You are the sum of how you rise after it.",
    author: "Unknown",
    category: "Self Love",
  ),
  Quote(
    text: "Berhenti meminta maaf untuk caramu tertawa, caramu berpakaian, dan caramu menjadi diri sendiri.",
    textEn: "Stop apologizing for how you laugh, how you dress, and for being yourself.",
    author: "Anonim",
    category: "Self Love",
  ),
  Quote(
    text: "Kamu adalah rumah bagi jiwamu sendiri. Rapikan, bersihkan, dan buatlah nyaman untuk ditinggali.",
    textEn: "You are a home for your own soul. Tidy it, clean it, and make it comfortable to live in.",
    author: "Bianca Sparacino",
    category: "Self Love",
  ),
  Quote(
    text: "Jangan menurunkan standarmu hanya karena kamu takut sendirian. Kualitas membutuhkan kesabaran.",
    textEn: "Don't lower your standards just because you're afraid of being alone. Quality takes patience.",
    author: "Unknown",
    category: "Self Love",
  ),
  Quote(
    text: "Kebahagiaan adalah pekerjaan orang dalam (inside job). Jangan menuntut orang lain untuk membahagiakanmu.",
    textEn: "Happiness is an inside job. Don't demand others to make you happy.",
    author: "Anonim",
    category: "Self Love",
  ),
  Quote(
    text: "Energimu mahal harganya. Jangan boroskan untuk meladeni drama yang tidak penting.",
    textEn: "Your energy is expensive. Don't waste it on unnecessary drama.",
    author: "Unknown",
    category: "Self Love",
  ),
  Quote(
    text: "Tuhan tidak menciptakan produk gagal. Kamu ada di sini karena kamu punya tujuan dan nilai.",
    textEn: "God doesn't create failed products. You are here because you have a purpose and value.",
    author: "Anonim",
    category: "Self Love",
  ),
  Quote(
    text: "Jadilah versi terbaik dari dirimu, bukan versi 'copy-paste' dari orang lain.",
    textEn: "Be the best version of yourself, not a copy-paste version of someone else.",
    author: "Judy Garland",
    category: "Self Love",
  ),
  Quote(
    text: "Self-care bukan egois, itu adalah manajemen energi agar kamu bisa berfungsi dengan baik.",
    textEn: "Self-care isn't selfish; it's energy management so you can function well.",
    author: "Unknown",
    category: "Self Love",
  ),
  Quote(
    text: "Jangan mengecilkan impianmu agar muat di dalam pikiran sempit orang lain.",
    textEn: "Don't shrink your dreams to fit into the narrow minds of others.",
    author: "Anonim",
    category: "Self Love",
  ),
  Quote(
    text: "Kamu lebih kuat dari overthinking-mu, dan lebih berharga dari insecurity-mu.",
    textEn: "You are stronger than your overthinking and more valuable than your insecurity.",
    author: "Unknown",
    category: "Self Love",
  ),
  Quote(
    text: "Detoksifikasi lingkunganmu dari orang-orang toxic sama pentingnya dengan makan sehat.",
    textEn: "Detoxifying your environment from toxic people is as important as eating healthy.",
    author: "Anonim",
    category: "Self Love",
  ),
  Quote(
    text: "Cintailah proses 'menjadi'. Kamu tidak harus selesai sekarang juga.",
    textEn: "Love the process of 'becoming'. You don't have to be finished right now.",
    author: "Unknown",
    category: "Self Love",
  ),
  Quote(
    text: "Berhenti mencari kebahagiaan di tempat yang sama di mana kamu kehilangannya.",
    textEn: "Stop searching for happiness in the same place where you lost it.",
    author: "Anonim",
    category: "Self Love",
  ),
  Quote(
    text: "Kamu tidak punya kewajiban untuk masuk akal bagi orang lain. Hidupmu, aturanmu.",
    textEn: "You have no obligation to make sense to others. Your life, your rules.",
    author: "Unknown",
    category: "Self Love",
  ),
  Quote(
    text: "Perlakukan dirimu dengan hormat, dan orang lain akan belajar cara memperlakukanmu dari situ.",
    textEn: "Treat yourself with respect, and others will learn how to treat you from that.",
    author: "Anonim",
    category: "Self Love",
  ),
  Quote(
    text: "Jangan biarkan satu bab yang buruk merusak keseluruhan buku kehidupanmu. Balik halamannya.",
    textEn: "Don't let one bad chapter ruin the whole book of your life. Turn the page.",
    author: "Unknown",
    category: "Self Love",
  ),
  Quote(
    text: "Kepercayaan diri bukanlah berpikir kamu lebih baik dari orang lain, tapi sadar kamu tidak perlu membandingkan diri.",
    textEn: "Confidence isn't thinking you're better than others, but realizing you don't need to compare yourself.",
    author: "Anonim",
    category: "Self Love",
  ),
  Quote(
    text: "Hatimu layak mendapatkan kedamaian, bukan kecemasan yang terus-menerus.",
    textEn: "Your heart deserves peace, not constant anxiety.",
    author: "Unknown",
    category: "Self Love",
  ),
  Quote(
    text: "Bersabarlah dengan dirimu sendiri. Kupu-kupu pun butuh waktu dalam kepompong sebelum terbang.",
    textEn: "Be patient with yourself. Even a butterfly needs time in its cocoon before flying.",
    author: "Anonim",
    category: "Self Love",
  ),
  Quote(
    text: "Memilih dirimu sendiri di atas orang yang menyakitimu bukanlah pengkhianatan, itu penyelamatan.",
    textEn: "Choosing yourself over those who hurt you isn't betrayal; it's a rescue.",
    author: "Unknown",
    category: "Self Love",
  ),
  Quote(
    text: "Syukuri nafasmu hari ini. Itu adalah hadiah yang sering kita lupakan saat sibuk mengeluh.",
    textEn: "Be grateful for your breath today. It's a gift we often forget while busy complaining.",
    author: "Anonim",
    category: "Self Love",
  ),
  Quote(
    text: "Kamu berhak bahagia hari ini, detik ini, tanpa harus menunggu sukses atau kaya dulu.",
    textEn: "You deserve to be happy today, this second, without having to wait to be successful or rich first.",
    author: "Unknown",
    category: "Self Love",
  ),
  Quote(
    text: "Jangan biarkan opini orang lain menenggelamkan suara hati kecilmu.",
    textEn: "Don't let the noise of others' opinions drown out your own inner voice.",
    author: "Steve Jobs",
    category: "Self Love",
  ),
  Quote(
    text: "Kamu tidak rusak, kamu hanya sedang dalam perbaikan (under construction).",
    textEn: "You are not broken; you are just under construction.",
    author: "Anonim",
    category: "Self Love",
  ),
  Quote(
    text: "Kecantikan hati tidak butuh filter kamera, ia memancar dari ketulusan.",
    textEn: "Inner beauty doesn't need a camera filter; it radiates from sincerity.",
    author: "Unknown",
    category: "Self Love",
  ),
  Quote(
    text: "Kamu adalah penulis cerita hidupmu. Jangan biarkan orang lain memegang penanya.",
    textEn: "You are the author of your life story. Don't let someone else hold the pen.",
    author: "Anonim",
    category: "Self Love",
  ),
  Quote(
    text: "Hargai batasanmu. Jika kamu selalu berkata 'ya', kamu sedang berkata 'tidak' pada kebutuhanmu sendiri.",
    textEn: "Respect your limits. If you always say 'yes', you are saying 'no' to your own needs.",
    author: "Unknown",
    category: "Self Love",
  ),
  Quote(
    text: "Kamu berharga bahkan saat kamu tidak melakukan apa-apa. Produktivitas tidak menentukan nilaimu.",
    textEn: "You are valuable even when you are doing nothing. Productivity does not determine your worth.",
    author: "Anonim",
    category: "Self Love",
  ),
  Quote(
    text: "Jatuh cinta pada dirimu sendiri adalah rahasia pertama menuju kebahagiaan.",
    textEn: "To fall in love with yourself is the first secret to happiness.",
    author: "Robert Morley",
    category: "Self Love",
  ),
  Quote(
    text: "Beranilah untuk tidak disukai demi mempertahankan integritas dirimu.",
    textEn: "Have the courage to be disliked to maintain your own integrity.",
    author: "Unknown",
    category: "Self Love",
  ),
  Quote(
    text: "Luka lama tidak akan sembuh jika kamu terus menyentuhnya dengan pikiran negatif.",
    textEn: "Old wounds won't heal if you keep touching them with negative thoughts.",
    author: "Anonim",
    category: "Self Love",
  ),
  Quote(
    text: "Hubungan paling lama yang akan kamu jalani adalah hubungan dengan dirimu sendiri.",
    textEn: "The longest relationship you will ever have is the one with yourself.",
    author: "Unknown",
    category: "Self Love",
  ),
  Quote(
    text: "Terkadang, hal paling produktif yang bisa kamu lakukan adalah rileks dan membiarkan dirimu bernapas.",
    textEn: "Sometimes the most productive thing you can do is relax and let yourself breathe.",
    author: "Mark Black",
    category: "Self Love",
  ),
  Quote(
    text: "Jangan takut berbeda, takutlah menjadi sama seperti orang lain dan kehilangan jati diri.",
    textEn: "Don't be afraid to be different; be afraid of being the same as everyone else and losing your identity.",
    author: "Anonim",
    category: "Self Love",
  ),
  Quote(
    text: "Kesuksesan terbesar adalah penerimaan diri yang utuh.",
    textEn: "The greatest success is wholehearted self-acceptance.",
    author: "Unknown",
    category: "Self Love",
  ),
  Quote(
    text: "Menjadi sensitif bukanlah kelemahan, itu berarti kamu punya hati yang hidup.",
    textEn: "Being sensitive is not a weakness; it means you have a living heart.",
    author: "Anonim",
    category: "Self Love",
  ),
  Quote(
    text: "Fokus pada langkahmu sendiri. Perlombaan lari tidak dimenangkan dengan menoleh ke pelari lain.",
    textEn: "Focus on your own steps. A race is not won by looking at other runners.",
    author: "Unknown",
    category: "Self Love",
  ),
  Quote(
    text: "Kamu layak dicintai tanpa syarat, bukan karena apa yang bisa kamu berikan.",
    textEn: "You deserve to be loved unconditionally, not because of what you can provide.",
    author: "Anonim",
    category: "Self Love",
  ),
  Quote(
    text: "Jangan menukar keaslian dirimu demi persetujuan orang lain.",
    textEn: "Don't trade your authenticity for the approval of others.",
    author: "Unknown",
    category: "Self Love",
  ),
  Quote(
    text: "Hiduplah di saat ini. Kecemasan adalah hidup di masa depan, penyesalan adalah hidup di masa lalu.",
    textEn: "Live in the moment. Anxiety is living in the future, regret is living in the past.",
    author: "Lao Tzu",
    category: "Self Love",
  ),
  Quote(
    text: "Jadilah pemaaf untuk dirimu sendiri, kamu belajar dan tumbuh setiap hari.",
    textEn: "Be forgiving to yourself; you learn and grow every day.",
    author: "Anonim",
    category: "Self Love",
  ),
  Quote(
    text: "Sinar matamu lebih berharga daripada kilau perhiasan manapun.",
    textEn: "The spark in your eyes is more valuable than the shine of any jewelry.",
    author: "Unknown",
    category: "Self Love",
  ),
  Quote(
    text: "Tidak ada orang lain yang bisa memainkan peranmu sebaik dirimu.",
    textEn: "No one else can play your role better than you.",
    author: "Anonim",
    category: "Self Love",
  ),
  Quote(
    text: "Kedamaian dimulai saat ekspektasi berakhir dan penerimaan dimulai.",
    textEn: "Peace begins where expectation ends and acceptance begins.",
    author: "Sri Chinmoy",
    category: "Self Love",
  ),
];