import '../models_daily_free/quote_model.dart';

List<Quote> logikaQuotes = [
  Quote(
    text: "Kita lebih sering menderita dalam imajinasi kita sendiri daripada dalam kenyataan.",
    textEn: "We suffer more often in imagination than in reality.",
    author: "Seneca",
    category: "Logika",
  ),
  Quote(
    text: "Kebahagiaan hidupmu bergantung pada kualitas pikiranmu.",
    textEn: "The happiness of your life depends upon the quality of your thoughts.",
    author: "Marcus Aurelius",
    category: "Logika",
  ),
  Quote(
    text: "Bukan kejadiannya yang mengganggu kita, tapi cara kita memandang kejadian tersebut.",
    textEn: "Men are disturbed not by things, but by the view which they take of them.",
    author: "Epictetus",
    category: "Logika",
  ),
  Quote(
    text: "Jangan menjelaskan dirimu kepada siapa pun. Karena yang menyukaimu tidak butuh itu, dan yang membencimu tidak akan percaya.",
    textEn: "Don't explain yourself to anyone. Because the one who likes you doesn't need it, and the one who hates you won't believe it.",
    author: "Ali bin Abi Thalib",
    category: "Logika",
  ),
  Quote(
    text: "Orang yang paling kuat bukanlah yang tak punya emosi, tapi yang bisa menjeda sejenak antara perasaan dan tindakan.",
    textEn: "The strongest person is not the one without emotions, but the one who can pause between feeling and action.",
    author: "Viktor Frankl",
    category: "Logika",
  ),
  Quote(
    text: "Jika kamu ingin menaklukkan kecemasan hidup, hiduplah di saat ini, hiduplah di nafas ini.",
    textEn: "If you want to conquer the anxiety of life, live in the moment, live in the breath.",
    author: "Amit Ray",
    category: "Logika",
  ),
  Quote(
    text: "Membalas kemarahan dengan kemarahan adalah membiarkan orang lain mengendalikan emosimu.",
    textEn: "Meeting anger with anger is allowing someone else to control your emotions.",
    author: "Anonim",
    category: "Logika",
  ),
  Quote(
    text: "Kekayaan sejati bukanlah memiliki banyak hal, tetapi menginginkan sedikit hal.",
    textEn: "Wealth consists not in having great possessions, but in having few wants.",
    author: "Epictetus",
    category: "Logika",
  ),
  Quote(
    text: "Kita tidak bisa memilih apa yang terjadi pada kita, tapi kita bisa memilih bagaimana meresponsnya.",
    textEn: "We cannot choose our external circumstances, but we can always choose how we respond to them.",
    author: "Stoic Wisdom",
    category: "Logika",
  ),
  Quote(
    text: "Fokuslah pada apa yang bisa kamu kendalikan, dan ikhlaskan apa yang di luar kendalimu.",
    textEn: "Focus on what you can control, and make peace with what you cannot.",
    author: "Epictetus",
    category: "Logika",
  ),
  Quote(
    text: "Jangan biarkan suara bising pendapat orang lain menenggelamkan suara hatimu sendiri.",
    textEn: "Don't let the noise of others' opinions drown out your own inner voice.",
    author: "Steve Jobs",
    category: "Logika",
  ),
  Quote(
    text: "Balas dendam terbaik adalah dengan tidak menjadi seperti orang yang menyakitimu.",
    textEn: "The best revenge is to be unlike him who performed the injury.",
    author: "Marcus Aurelius",
    category: "Logika",
  ),
  Quote(
    text: "Ketenangan adalah kekuatan. Emosi yang terkendali adalah tanda kedewasaan logika.",
    textEn: "Calmness is power. Controlled emotion is the mark of logical maturity.",
    author: "Anonim",
    category: "Logika",
  ),
  Quote(
    text: "Siapa yang tidak bisa memaafkan orang lain, menghancurkan jembatan yang harus ia lewati sendiri.",
    textEn: "He that cannot forgive others breaks the bridge over which he must pass himself.",
    author: "Francis Bacon",
    category: "Logika",
  ),
  Quote(
    text: "Hidup yang tidak direfleksikan tidak layak untuk dijalani.",
    textEn: "The unexamined life is not worth living.",
    author: "Socrates",
    category: "Logika",
  ),
  Quote(
    text: "Dua hal mendefinisikanmu: Kesabaranmu saat tidak memiliki apa-apa, dan sikapmu saat memiliki segalanya.",
    textEn: "Two things define you: Your patience when you have nothing, and your attitude when you have everything.",
    author: "Imam Al-Ghazali",
    category: "Logika",
  ),
  Quote(
    text: "Jangan berharap dunia adil padamu karena kamu baik. Itu sama seperti berharap singa tidak memakanmu karena kamu vegetarian.",
    textEn: "Don't expect the world to be fair to you because you are good. That's like expecting a lion not to eat you because you're a vegetarian.",
    author: "Anonim",
    category: "Logika",
  ),
  Quote(
    text: "Orang pintar memecahkan masalah. Orang bijak menghindarinya.",
    textEn: "A clever person solves a problem. A wise person avoids it.",
    author: "Albert Einstein",
    category: "Logika",
  ),
  Quote(
    text: "Keinginan adalah kontrak yang kamu buat dengan dirimu sendiri untuk tidak bahagia sampai kamu mendapatkan apa yang kamu inginkan.",
    textEn: "Desire is a contract you make with yourself to be unhappy until you get what you want.",
    author: "Naval Ravikant",
    category: "Logika",
  ),
  Quote(
    text: "Masalahnya bukan masalah itu sendiri. Masalahnya adalah sikapmu terhadap masalah itu.",
    textEn: "The problem is not the problem. The problem is your attitude about the problem.",
    author: "Kapten Jack Sparrow",
    category: "Logika",
  ),
  Quote(
    text: "Jika kamu tertekan oleh hal eksternal, rasa sakit itu bukan karena hal itu, tapi karena estimasimu sendiri mengenainya.",
    textEn: "If you are distressed by anything external, the pain is not due to the thing itself, but to your estimate of it.",
    author: "Marcus Aurelius",
    category: "Logika",
  ),
  Quote(
    text: "Waktu yang kamu nikmati untuk dihabiskan bukanlah waktu yang terbuang.",
    textEn: "Time you enjoy wasting is not wasted time.",
    author: "Marthe Troly-Curtin",
    category: "Logika",
  ),
  Quote(
    text: "Berhenti overthinking. Kamu tidak bisa mengontrol segalanya, tapi kamu bisa mengontrol iman dan usahamu.",
    textEn: "Stop overthinking. You can't control everything, but you can control your faith and your effort.",
    author: "Original",
    category: "Logika",
  ),
  Quote(
    text: "Banyak orang mati di usia 25 tahun, tapi baru dikuburkan di usia 75 tahun.",
    textEn: "Many people die at twenty-five and aren't buried until they are seventy-five.",
    author: "Benjamin Franklin",
    category: "Logika",
  ),
  Quote(
    text: "Keberanian bukanlah ketiadaan rasa takut, tetapi penilaian bahwa ada sesuatu yang lebih penting daripada rasa takut.",
    textEn: "Courage is not the absence of fear, but rather the assessment that something else is more important than fear.",
    author: "Ambrose Redmoon",
    category: "Logika",
  ),
  Quote(
    text: "Jangan menukar apa yang paling kamu inginkan dalam hidup dengan apa yang kamu inginkan saat ini.",
    textEn: "Never trade what you want most in life for what you want at the moment.",
    author: "Zig Ziglar",
    category: "Logika",
  ),
  Quote(
    text: "Semakin tenang dirimu, semakin jernih kamu berpikir.",
    textEn: "The calmer you are, the clearer you think.",
    author: "Original",
    category: "Logika",
  ),
  Quote(
    text: "Lidahmu jangan kamu biarkan menyebut kekurangan orang lain, sebab kamu pun punya kekurangan dan orang lain pun punya lidah.",
    textEn: "Do not let your tongue mention the faults of others, for you also have faults and others have tongues.",
    author: "Imam Syafi'i",
    category: "Logika",
  ),
  Quote(
    text: "Kesombongan adalah pengakuan akan kelemahan. Orang yang benar-benar kuat tidak butuh validasi.",
    textEn: "Pride is an admission of weakness. Truly strong people don't need validation.",
    author: "Original",
    category: "Logika",
  ),
  Quote(
    text: "Satu-satunya cara untuk menang dalam perdebatan beracun adalah dengan tidak berpartisipasi.",
    textEn: "The only way to win a toxic argument is to not participate.",
    author: "Original",
    category: "Logika",
  ),
  Quote(
    text: "Jika kamu mencari kesempurnaan, kamu tidak akan pernah tenang.",
    textEn: "If you look for perfection, you'll never be content.",
    author: "Leo Tolstoy",
    category: "Logika",
  ),
  Quote(
    text: "Menerima kenyataan pahit lebih baik daripada hidup dalam ilusi manis yang menipu.",
    textEn: "Accepting a bitter reality is better than living in a sweet, deceptive illusion.",
    author: "Original",
    category: "Logika",
  ),
  Quote(
    text: "Jangan biarkan perilaku orang lain menghancurkan kedamaian batinmu.",
    textEn: "Do not let the behavior of others destroy your inner peace.",
    author: "Dalai Lama",
    category: "Logika",
  ),
  Quote(
    text: "Kamu menjadi apa yang kamu beri perhatian.",
    textEn: "You become what you give your attention to.",
    author: "Stoic Wisdom",
    category: "Logika",
  ),
  Quote(
    text: "Pikiran yang cemas menderita dua kali: sebelum masalah datang dan saat masalah itu benar-benar datang.",
    textEn: "An anxious mind suffers twice: before the problem arrives and when it actually does.",
    author: "Original",
    category: "Logika",
  ),
  Quote(
    text: "Belajarlah untuk tidak peduli pada hal yang tidak penting, itu adalah seni tertinggi dalam menjaga kewarasan.",
    textEn: "Learn to be indifferent to what makes no difference; it is the highest art of maintaining sanity.",
    author: "Original",
    category: "Logika",
  ),
  Quote(
    text: "Jadilah seperti karang, ombak terus menghantamnya, namun ia tetap berdiri teguh dan menjinakkan amarah air di sekelilingnya.",
    textEn: "Be like the promontory against which the waves continually break, but it stands firm and tames the fury of the water around it.",
    author: "Marcus Aurelius",
    category: "Logika",
  ),
  Quote(
    text: "Menunda pekerjaan yang sulit hanya membuat pekerjaan itu semakin menakutkan.",
    textEn: "Delaying difficult work only makes it more daunting.",
    author: "Original",
    category: "Logika",
  ),
  Quote(
    text: "Validasi terbaik datang dari cermin, bukan dari 'likes' di media sosial.",
    textEn: "The best validation comes from the mirror, not from 'likes' on social media.",
    author: "Original",
    category: "Logika",
  ),
  Quote(
    text: "Dunia ini adalah komedi bagi mereka yang berpikir, dan tragedi bagi mereka yang merasa.",
    textEn: "The world is a comedy to those that think, a tragedy to those that feel.",
    author: "Horace Walpole",
    category: "Logika",
  ),
  Quote(
    text: "Kesulitan seringkali mempersiapkan orang biasa untuk takdir yang luar biasa.",
    textEn: "Hardships often prepare ordinary people for an extraordinary destiny.",
    author: "C.S. Lewis",
    category: "Logika",
  ),
  Quote(
    text: "Jangan takut berjalan lambat, takutlah jika kamu hanya berdiri diam.",
    textEn: "Be not afraid of going slowly, be afraid only of standing still.",
    author: "Peribahasa Tiongkok",
    category: "Logika",
  ),
  Quote(
    text: "Logika membawamu dari A ke B. Imajinasi membawamu ke mana-mana.",
    textEn: "Logic will get you from A to B. Imagination will take you everywhere.",
    author: "Albert Einstein",
    category: "Logika",
  ),
  Quote(
    text: "Bukan beban yang menghancurkanmu, tapi cara kamu membawanya.",
    textEn: "It's not the load that breaks you down, it's the way you carry it.",
    author: "Lou Holtz",
    category: "Logika",
  ),
  Quote(
    text: "Kekecewaan adalah cara Tuhan mengatakan: 'Bersabarlah, Aku punya sesuatu yang lebih baik untukmu'.",
    textEn: "Disappointment is God's way of saying: 'Be patient, I have something better for you'.",
    author: "Anonim",
    category: "Logika",
  ),
  Quote(
    text: "Diam seringkali merupakan jawaban terbaik untuk pertanyaan yang bodoh.",
    textEn: "Silence is often the best answer to a foolish question.",
    author: "Original",
    category: "Logika",
  ),
  Quote(
    text: "Jangan bakar rumahmu hanya untuk membunuh tikus. Jangan hancurkan harimu karena satu masalah kecil.",
    textEn: "Don't burn your house down just to kill a rat. Don't ruin your day over one small problem.",
    author: "Original",
    category: "Logika",
  ),
  Quote(
    text: "Masa lalu sudah mati, masa depan belum lahir. Hiduplah hari ini.",
    textEn: "The past is dead, the future is unborn. Live today.",
    author: "Buddhisme",
    category: "Logika",
  ),
  Quote(
    text: "Kematangan adalah ketika kamu menyadari bahwa tidak semua hal butuh komentarmu.",
    textEn: "Maturity is when you realize that not everything requires your comment.",
    author: "Original",
    category: "Logika",
  ),
  Quote(
    text: "Harta yang paling berharga adalah ketenangan jiwa, yang tidak bisa dibeli dengan uang.",
    textEn: "The most valuable treasure is peace of mind, which cannot be bought with money.",
    author: "Original",
    category: "Logika",
  ),
  Quote(
    text: "Seseorang yang berani membuang satu jam waktunya, belum mengetahui nilai kehidupan.",
    textEn: "A man who dares to waste one hour of time has not discovered the value of life.",
    author: "Charles Darwin",
    category: "Logika",
  ),
  Quote(
    text: "Logika tanpa hati itu keras, hati tanpa logika itu buta.",
    textEn: "Logic without heart is harsh, heart without logic is blind.",
    author: "Original",
    category: "Logika",
  ),
  Quote(
    text: "Kemarin saya pintar, jadi saya ingin mengubah dunia. Hari ini saya bijaksana, jadi saya mengubah diri sendiri.",
    textEn: "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.",
    author: "Jalaluddin Rumi",
    category: "Logika",
  ),
  Quote(
    text: "Jangan habiskan waktumu berdebat tentang seperti apa orang baik itu. Jadilah satu.",
    textEn: "Waste no more time arguing about what a good man should be. Be one.",
    author: "Marcus Aurelius",
    category: "Logika",
  ),
  Quote(
    text: "Tidak ada orang yang bebas jika ia tidak bisa menguasai dirinya sendiri.",
    textEn: "No man is free who cannot control himself.",
    author: "Epictetus",
    category: "Logika",
  ),
  Quote(
    text: "Sabar itu ilmu tingkat tinggi. Belajarnya setiap hari, latihannya setiap saat, ujiannya mendadak.",
    textEn: "Patience is high-level science. You learn it daily, practice it constantly, and the tests are always unannounced.",
    author: "Original",
    category: "Logika",
  ),
  Quote(
    text: "Khawatir itu seperti membayar bunga untuk utang yang belum tentu kamu miliki.",
    textEn: "Worrying is like paying interest on a debt you may never owe.",
    author: "Mark Twain",
    category: "Logika",
  ),
  Quote(
    text: "Seringkali, kita takut bukan karena tantangannya sulit, tapi karena kita membayangkan hal terburuk yang belum terjadi.",
    textEn: "We are often afraid not because the challenge is hard, but because we imagine the worst that hasn't happened.",
    author: "Seneca",
    category: "Logika",
  ),
  Quote(
    text: "Jika kamu depresi, kamu hidup di masa lalu. Jika cemas, kamu hidup di masa depan. Jika tenang, kamu hidup di masa kini.",
    textEn: "If you are depressed, you are living in the past. If you are anxious, you are living in the future. If you are at peace, you are living in the present.",
    author: "Lao Tzu",
    category: "Logika",
  ),
  Quote(
    text: "Kedewasaan adalah ketika kamu memilih diam daripada membuktikan bahwa kamu benar kepada orang yang tidak mau mengerti.",
    textEn: "Maturity is when you choose silence over proving you're right to someone who refuses to understand.",
    author: "Original",
    category: "Logika",
  ),
  Quote(
    text: "Marah itu gampang. Tapi marah kepada orang yang tepat, dengan kadar yang tepat, di saat yang tepat, itu sulit.",
    textEn: "Anyone can become angry�that is easy. But to be angry with the right person, and to the right degree, and at the right time, is not easy.",
    author: "Aristoteles",
    category: "Logika",
  ),
  Quote(
    text: "Jangan biarkan pujian masuk ke kepala, dan jangan biarkan kritikan masuk ke hati.",
    textEn: "Don't let praise go to your head, and don't let criticism go to your heart.",
    author: "Original",
    category: "Logika",
  ),
  Quote(
    text: "Perbandingan adalah pencuri kebahagiaan. Fokus pada jalurmu sendiri.",
    textEn: "Comparison is the thief of joy. Focus on your own path.",
    author: "Theodore Roosevelt",
    category: "Logika",
  ),
  Quote(
    text: "Kesulitanlah yang membangun karakter, seperti api yang memurnikan emas.",
    textEn: "Difficulty builds character, like fire purifies gold.",
    author: "Seneca",
    category: "Logika",
  ),
  Quote(
    text: "Bukan tugasmu untuk membuat semua orang menyukaimu. Tugasmu adalah menyukai dirimu sendiri apa adanya.",
    textEn: "It is not your job to make everyone like you. It is your job to like yourself as you are.",
    author: "Original",
    category: "Logika",
  ),
  Quote(
    text: "Mengetahui orang lain adalah kecerdasan; mengetahui diri sendiri adalah kebijaksanaan sejati.",
    textEn: "Knowing others is intelligence; knowing yourself is true wisdom.",
    author: "Lao Tzu",
    category: "Logika",
  ),
  Quote(
    text: "Dunia berubah ketika kita merubah cara pandang kita terhadapnya.",
    textEn: "The world changes when we change the way we look at it.",
    author: "Original",
    category: "Logika",
  ),
  Quote(
    text: "Jangan menunda kebahagiaanmu demi pencapaian di masa depan. Berbahagialah dalam prosesnya.",
    textEn: "Don't postpone your happiness for future achievements. Be happy in the process.",
    author: "Original",
    category: "Logika",
  ),
  Quote(
    text: "Lidah yang tajam adalah satu-satunya alat pemotong yang semakin tajam jika sering digunakan.",
    textEn: "A sharp tongue is the only edged tool that grows keener with constant use.",
    author: "Washington Irving",
    category: "Logika",
  ),
  Quote(
    text: "Hiduplah seolah-olah kamu akan mati besok. Belajarlah seolah-olah kamu akan hidup selamanya.",
    textEn: "Live as if you were to die tomorrow. Learn as if you were to live forever.",
    author: "Mahatma Gandhi",
    category: "Logika",
  ),
  Quote(
    text: "Pohon yang paling kuat tumbuh di tanah yang paling keras dan diterpa angin paling kencang.",
    textEn: "The strongest trees grow on the hardest ground and are buffeted by the fiercest winds.",
    author: "J. Willard Marriott",
    category: "Logika",
  ),
  Quote(
    text: "Emosi adalah data, bukan instruksi. Rasakan, tapi jangan langsung dituruti tanpa logika.",
    textEn: "Emotions are data, not instructions. Feel them, but don't act blindly without logic.",
    author: "Susan David",
    category: "Logika",
  ),
  Quote(
    text: "Jangan membenci apa yang tidak kamu pahami.",
    textEn: "Do not hate what you do not understand.",
    author: "Ali bin Abi Thalib",
    category: "Logika",
  ),
  Quote(
    text: "Kemenangan sejati bukanlah mengalahkan musuh yang kuat, tapi mengalahkan hawa nafsu sendiri.",
    textEn: "True victory is not defeating a strong enemy, but defeating one's own desires.",
    author: "Imam Al-Ghazali",
    category: "Logika",
  ),
  Quote(
    text: "Keberuntungan adalah pertemuan antara persiapan dan kesempatan.",
    textEn: "Luck is what happens when preparation meets opportunity.",
    author: "Seneca",
    category: "Logika",
  ),
  Quote(
    text: "Lebih baik diam dan terlihat bodoh daripada bicara dan menghilangkan keraguan orang tentang kebodohanmu.",
    textEn: "Better to remain silent and be thought a fool than to speak and remove all doubt.",
    author: "Abraham Lincoln",
    category: "Logika",
  ),
  Quote(
    text: "Jadilah seperti air. Tidak melawan rintangan, tapi mengalir melaluinya.",
    textEn: "Be like water. Not fighting obstacles, but flowing through them.",
    author: "Bruce Lee",
    category: "Logika",
  ),
  Quote(
    text: "Hidup ini 10% apa yang terjadi padamu dan 90% bagaimana kamu bereaksi terhadapnya.",
    textEn: "Life is 10% what happens to you and 90% how you react to it.",
    author: "Charles R. Swindoll",
    category: "Logika",
  ),
  Quote(
    text: "Memiliki sedikit keinginan adalah jalan pintas menuju kekayaan.",
    textEn: "He is richest who is content with the least.",
    author: "Socrates",
    category: "Logika",
  ),
  Quote(
    text: "Waktu adalah guru terbaik, tapi sayangnya ia membunuh semua muridnya.",
    textEn: "Time is a great teacher, but unfortunately it kills all its pupils.",
    author: "Hector Berlioz",
    category: "Logika",
  ),
  Quote(
    text: "Orang bijak belajar dari kesalahan orang lain, orang bodoh belajar dari kesalahannya sendiri.",
    textEn: "Wise men learn by others' mistakes; fools by their own.",
    author: "Pepatah Latin",
    category: "Logika",
  ),
  Quote(
    text: "Ketenangan bukan berarti tidak ada badai, tapi kedamaian di tengah badai.",
    textEn: "Calmness does not mean the absence of a storm, but peace in the midst of it.",
    author: "Original",
    category: "Logika",
  ),
  Quote(
    text: "Jika kamu ingin dihormati, hormatilah dirimu sendiri dengan menjaga integritasmu.",
    textEn: "If you want to be respected, respect yourself by maintaining your integrity.",
    author: "Original",
    category: "Logika",
  ),
  Quote(
    text: "Menyimpan dendam itu seperti meminum racun dan berharap orang lain yang mati.",
    textEn: "Holding onto anger is like drinking poison and expecting the other person to die.",
    author: "Buddha",
    category: "Logika",
  ),
  Quote(
    text: "Seseorang yang memindahkan gunung memulai dengan memindahkan batu-batu kecil.",
    textEn: "The man who moves a mountain begins by carrying away small stones.",
    author: "Confucius",
    category: "Logika",
  ),
  Quote(
    text: "Logika membuatmu tetap hidup, tapi harapan membuatmu tetap bersemangat.",
    textEn: "Logic keeps you alive, but hope keeps you vibrant.",
    author: "Original",
    category: "Logika",
  ),
  Quote(
    text: "Cermin terbaik adalah sahabat lama.",
    textEn: "The best mirror is an old friend.",
    author: "George Herbert",
    category: "Logika",
  ),
  Quote(
    text: "Jangan takut berjalan sendirian. Singa tidak berjalan dalam kawanan seperti domba.",
    textEn: "Don't be afraid to walk alone. Lions don't walk in herds like sheep.",
    author: "Original",
    category: "Logika",
  ),
  Quote(
    text: "Amor Fati: Cintailah takdirmu, apapun yang terjadi, karena itulah jalanmu.",
    textEn: "Amor Fati: Love your fate, no matter what happens, for that is your path.",
    author: "Friedrich Nietzsche",
    category: "Logika",
  ),
  Quote(
    text: "Kesibukan bukanlah produktivitas. Jangan keliru mengartikan gerakan dengan kemajuan.",
    textEn: "Don't mistake movement for achievement. Busyness is not productivity.",
    author: "Denzel Washington",
    category: "Logika",
  ),
  Quote(
    text: "Solusi dari masalahmu seringkali ada dalam keheningan, bukan dalam keramaian pikiran.",
    textEn: "The solution to your problem often lies in silence, not in the noise of the mind.",
    author: "Original",
    category: "Logika",
  ),
  Quote(
    text: "Kesehatan bukan segalanya, tapi tanpa kesehatan, segalanya bukan apa-apa.",
    textEn: "Health is not everything, but without health, everything is nothing.",
    author: "Schopenhauer",
    category: "Logika",
  ),
  Quote(
    text: "Jangan biarkan internet memburumu. Hidupmu ada di sini, bukan di layar.",
    textEn: "Don't let the internet hunt you. Your life is here, not on the screen.",
    author: "Original",
    category: "Logika",
  ),
  Quote(
    text: "Ilmu tanpa akal ibarat memiliki sepatu tanpa kaki. Akal tanpa ilmu ibarat memiliki kaki tanpa sepatu.",
    textEn: "Knowledge without reason is like having shoes without feet. Reason without knowledge is like having feet without shoes.",
    author: "Ali bin Abi Thalib",
    category: "Logika",
  ),
  Quote(
    text: "Kita tidak mewarisi bumi dari nenek moyang, kita meminjamnya dari anak cucu kita.",
    textEn: "We do not inherit the earth from our ancestors, we borrow it from our children.",
    author: "Pepatah Indian",
    category: "Logika",
  ),
  Quote(
    text: "Kegagalan hanyalah kesempatan untuk memulai lagi, kali ini dengan lebih cerdas.",
    textEn: "Failure is simply the opportunity to begin again, this time more intelligently.",
    author: "Henry Ford",
    category: "Logika",
  ),
  Quote(
    text: "Jangan berusaha menjadi manusia yang sukses, tapi berusahalah menjadi manusia yang bernilai.",
    textEn: "Try not to become a man of success, but rather try to become a man of value.",
    author: "Albert Einstein",
    category: "Logika",
  ),
  Quote(
    text: "Setiap orang yang kamu temui tahu sesuatu yang tidak kamu ketahui. Belajarlah dari mereka.",
    textEn: "Everyone you will ever meet knows something you don't. Learn from them.",
    author: "Bill Nye",
    category: "Logika",
  ),
  Quote(
    text: "Rasa sakit itu tidak terhindarkan, tapi menderita itu pilihan.",
    textEn: "Pain is inevitable. Suffering is optional.",
    author: "Haruki Murakami",
    category: "Logika",
  ),
  Quote(
    text: "Hati yang damai adalah akar dari tubuh yang sehat.",
    textEn: "A peaceful heart gives life to the body.",
    author: "Amsal",
    category: "Logika",
  ),
];