import '../models_daily_free/quote_model.dart';

List<Quote> semangatQuotes = [
  Quote(
    text: "Jangan menunggu waktu yang tepat, karena waktu tidak akan pernah tepat. Mulailah sekarang.",
    textEn: "Don't wait. The time will never be just right. Start where you stand.",
    author: "Napoleon Hill",
    category: "Semangat",
  ),
  Quote(
    text: "Satu-satunya cara untuk melakukan pekerjaan hebat adalah dengan mencintai apa yang kamu lakukan.",
    textEn: "The only way to do great work is to love what you do.",
    author: "Steve Jobs",
    category: "Semangat",
  ),
  Quote(
    text: "Maka sesungguhnya bersama kesulitan ada kemudahan. Tetaplah berjuang.",
    textEn: "For indeed, with hardship comes ease. Keep fighting.",
    author: "QS. Al-Insyirah: 5-6",
    category: "Semangat",
  ),
  Quote(
    text: "Orang yang paling berani adalah orang yang takut kepada Allah, namun tetap melangkah maju demi kebaikan.",
    textEn: "The bravest person is the one who fears Allah, yet continues to step forward for the sake of goodness.",
    author: "Umar bin Khattab",
    category: "Semangat",
  ),
  Quote(
    text: "Jangan menjelaskan tentang dirimu kepada siapapun, karena yang menyukaimu tidak butuh itu, dan yang membencimu tidak percaya itu.",
    textEn: "Do not explain yourself to anyone, for the one who likes you doesn't need it, and the one who hates you won't believe it.",
    author: "Ali bin Abi Thalib",
    category: "Semangat",
  ),
  Quote(
    text: "Kegagalan hanya terjadi bila kita menyerah.",
    textEn: "Failure only happens when we give up.",
    author: "B.J. Habibie",
    category: "Semangat",
  ),
  Quote(
    text: "Tugas kita bukanlah untuk berhasil. Tugas kita adalah untuk mencoba, karena di dalam mencoba itulah kita menemukan dan belajar membangun kesempatan untuk berhasil.",
    textEn: "Our task is not to succeed. Our task is to try, for it is in trying that we find and learn to build the opportunity to succeed.",
    author: "Buya Hamka",
    category: "Semangat",
  ),
  Quote(
    text: "Lelahmu akan menjadi lillah jika niatmu untuk ibadah dan kebaikan.",
    textEn: "Your exhaustion will become a blessing (lillah) if your intention is for worship and goodness.",
    author: "Nasehat Ulama",
    category: "Semangat",
  ),
  Quote(
    text: "Barangsiapa yang bersungguh-sungguh, maka dia akan mendapatkan kesuksesan.",
    textEn: "He who strives with sincerity shall find success. (Man Jadda Wajada)",
    author: "Pepatah Arab",
    category: "Semangat",
  ),
  Quote(
    text: "Perjalanan seribu mil dimulai dengan satu langkah kecil.",
    textEn: "A journey of a thousand miles begins with a single step.",
    author: "Lao Tzu",
    category: "Semangat",
  ),
  Quote(
    text: "Jangan biarkan hari kemarin menyita terlalu banyak hari inimu.",
    textEn: "Don't let yesterday take up too much of today.",
    author: "Will Rogers",
    category: "Semangat",
  ),
  Quote(
    text: "Jika kamu tidak bisa terbang, maka larilah. Jika tidak bisa lari, berjalanlah. Apapun yang terjadi, teruslah bergerak maju.",
    textEn: "If you can't fly then run, if you can't run then walk. Whatever happens, keep moving forward.",
    author: "Martin Luther King Jr.",
    category: "Semangat",
  ),
  Quote(
    text: "Rezeki itu sudah tertakar, tidak akan tertukar. Tugas kita hanya berikhtiar dengan benar.",
    textEn: "Fortune is already measured and will never be misplaced. Our only duty is to strive correctly.",
    author: "Anonim",
    category: "Semangat",
  ),
  Quote(
    text: "Rahasia untuk maju adalah memulai.",
    textEn: "The secret of getting ahead is getting started.",
    author: "Mark Twain",
    category: "Semangat",
  ),
  Quote(
    text: "Masa depan adalah milik mereka yang percaya pada keindahan mimpi-mimpi mereka.",
    textEn: "The future belongs to those who believe in the beauty of their dreams.",
    author: "Eleanor Roosevelt",
    category: "Semangat",
  ),
  Quote(
    text: "Allah tidak membebani seseorang melainkan sesuai dengan kesanggupannya.",
    textEn: "Allah does not burden a soul beyond that it can bear.",
    author: "QS. Al-Baqarah: 286",
    category: "Semangat",
  ),
  Quote(
    text: "Jangan takut gagal, takutlah jika kamu tidak pernah mencoba.",
    textEn: "Do not fear failure, but be afraid if you never try.",
    author: "Anonim",
    category: "Semangat",
  ),
  Quote(
    text: "Ilmu itu didapat dengan lidah yang gemar bertanya dan akal yang suka berpikir.",
    textEn: "Knowledge is acquired through a tongue that loves to ask and a mind that loves to think.",
    author: "Abdullah bin Abbas",
    category: "Semangat",
  ),
  Quote(
    text: "Kesabaran itu pahit, tapi buahnya lebih manis daripada madu.",
    textEn: "Patience is bitter, but its fruit is sweeter than honey.",
    author: "Imam Syafi'i",
    category: "Semangat",
  ),
  Quote(
    text: "Bekerjalah seakan-akan kamu hidup selamanya, dan beribadahlah seakan-akan kamu mati besok.",
    textEn: "Work as if you were to live forever, and pray as if you were to die tomorrow.",
    author: "Nasehat Bijak",
    category: "Semangat",
  ),
  Quote(
    text: "Orang sukses tidak santai, orang santai tidak sukses.",
    textEn: "Successful people don't relax, and relaxed people don't succeed.",
    author: "Anonim",
    category: "Semangat",
  ),
  Quote(
    text: "Setiap pagi kita punya dua pilihan: Terus tidur dengan mimpi kita, atau bangun dan mengejarnya.",
    textEn: "Every morning we have two choices: Continue to sleep with your dreams, or wake up and chase them.",
    author: "Anonim",
    category: "Semangat",
  ),
  Quote(
    text: "Kualitas hidupmu ditentukan oleh kualitas pikiranmu. Berpikirlah positif.",
    textEn: "The quality of your life is determined by the quality of your thoughts. Think positive.",
    author: "Marcus Aurelius",
    category: "Semangat",
  ),
  Quote(
    text: "Jangan membandingkan prosesmu dengan orang lain. Bunga tidak mekar secara bersamaan.",
    textEn: "Don't compare your progress with others. Flowers do not bloom at the same time.",
    author: "Zen Quotes",
    category: "Semangat",
  ),
  Quote(
    text: "Hiduplah seolah-olah kamu akan mati besok. Belajarlah seolah-olah kamu akan hidup selamanya.",
    textEn: "Live as if you were to die tomorrow. Learn as if you were to live forever.",
    author: "Mahatma Gandhi",
    category: "Semangat",
  ),
  Quote(
    text: "Usaha tidak akan pernah mengkhianati hasil.",
    textEn: "Hard work will never betray the results.",
    author: "Pepatah Populer",
    category: "Semangat",
  ),
  Quote(
    text: "Jadilah seperti mata air yang jernih, yang memberikan kehidupan kepada sekitarnya.",
    textEn: "Be like a clear spring, providing life to everything around it.",
    author: "Imam Al-Ghazali",
    category: "Semangat",
  ),
  Quote(
    text: "Ketakutan membunuh lebih banyak mimpi daripada kegagalan.",
    textEn: "Fear kills more dreams than failure ever will.",
    author: "Suzy Kassem",
    category: "Semangat",
  ),
  Quote(
    text: "Bukan seberapa cepat kamu berlari, tapi seberapa kuat kamu bertahan.",
    textEn: "It�s not about how fast you run, but how strong you endure.",
    author: "Anonim",
    category: "Semangat",
  ),
  Quote(
    text: "Sebaik-baik manusia adalah yang paling bermanfaat bagi manusia lain.",
    textEn: "The best of people are those who are most beneficial to others.",
    author: "Hadits Riwayat Ahmad",
    category: "Semangat",
  ),
  Quote(
    text: "Disiplin adalah melakukan apa yang harus dilakukan, bahkan ketika kamu tidak ingin melakukannya.",
    textEn: "Discipline is doing what needs to be done, even when you don't want to do it.",
    author: "Anonim",
    category: "Semangat",
  ),
  Quote(
    text: "Sukses adalah jumlah dari upaya kecil yang diulangi hari demi hari.",
    textEn: "Success is the sum of small efforts, repeated day in and day out.",
    author: "Robert Collier",
    category: "Semangat",
  ),
  Quote(
    text: "Jangan mengharapkan jalan yang mudah, tapi mintalah bahu yang kuat.",
    textEn: "Do not pray for an easy life, pray for the strength to endure a difficult one.",
    author: "Anonim",
    category: "Semangat",
  ),
  Quote(
    text: "Waktu bagaikan pedang. Jika engkau tidak memanfaatkannya, ia akan memotongmu.",
    textEn: "Time is like a sword. If you do not use it, it will cut you.",
    author: "Pepatah Arab",
    category: "Semangat",
  ),
  Quote(
    text: "Bekerja keraslah dalam diam, biarkan kesuksesanmu yang membuat keributan.",
    textEn: "Work hard in silence, let your success be your noise.",
    author: "Frank Ocean",
    category: "Semangat",
  ),
  Quote(
    text: "Optimisme adalah iman yang menuntun pada pencapaian.",
    textEn: "Optimism is the faith that leads to achievement.",
    author: "Helen Keller",
    category: "Semangat",
  ),
  Quote(
    text: "Dunia ini ibarat bayangan. Jika kau berusaha menangkapnya, ia akan lari. Tapi jika kau membelakanginya, ia tak punya pilihan selain mengikutimu.",
    textEn: "This world is like a shadow. If you try to catch it, it will run. But if you turn your back on it, it has no choice but to follow you.",
    author: "Ibnu Qayyim Al-Jauziyyah",
    category: "Semangat",
  ),
  Quote(
    text: "Kesempatan biasanya menyamar sebagai kerja keras, itulah sebabnya kebanyakan orang tidak mengenalinya.",
    textEn: "Opportunity is missed by most people because it is dressed in overalls and looks like work.",
    author: "Ann Landers",
    category: "Semangat",
  ),
  Quote(
    text: "Berlomba-lombalah dalam kebaikan.",
    textEn: "Race with one another in doing good.",
    author: "QS. Al-Baqarah: 148",
    category: "Semangat",
  ),
  Quote(
    text: "Pikiranmu adalah senjata terkuatmu. Pastikan ia terisi dengan peluru positif.",
    textEn: "Your mind is your strongest weapon. Ensure it is loaded with positive bullets.",
    author: "Anonim",
    category: "Semangat",
  ),
  Quote(
    text: "Jangan menyerah saat doa-doamu belum terjawab. Jika kamu mampu bersabar, Allah mampu memberikan lebih dari yang kamu minta.",
    textEn: "Don't give up when your prayers are yet unanswered. If you can be patient, Allah can give you more than you asked for.",
    author: "Anonim",
    category: "Semangat",
  ),
  Quote(
    text: "Setiap ahli dulunya adalah seorang pemula.",
    textEn: "Every expert was once a beginner.",
    author: "Robin Sharma",
    category: "Semangat",
  ),
  Quote(
    text: "Jika rencanamu tidak berhasil, ubah rencananya, bukan tujuannya.",
    textEn: "If the plan doesn't work, change the plan, but never the goal.",
    author: "Anonim",
    category: "Semangat",
  ),
  Quote(
    text: "Hambatan adalah hal-hal menakutkan yang kamu lihat ketika kamu mengalihkan pandangan dari tujuanmu.",
    textEn: "Obstacles are those frightful things you see when you take your eyes off your goal.",
    author: "Henry Ford",
    category: "Semangat",
  ),
  Quote(
    text: "Syukur adalah cara termudah untuk menarik lebih banyak kebaikan dalam hidupmu.",
    textEn: "Gratitude is the easiest way to attract more goodness into your life.",
    author: "Anonim",
    category: "Semangat",
  ),
  Quote(
    text: "Jadilah pemaaf, demi kedamaian hatimu sendiri.",
    textEn: "Be forgiving, for the sake of your own heart's peace.",
    author: "Nasehat Bijak",
    category: "Semangat",
  ),
  Quote(
    text: "Cara terbaik memprediksi masa depan adalah dengan menciptakannya.",
    textEn: "The best way to predict the future is to create it.",
    author: "Peter Drucker",
    category: "Semangat",
  ),
  Quote(
    text: "Lakukanlah kebaikan sekecil apapun, karena kau tidak pernah tahu kebaikan mana yang akan membawamu ke surga.",
    textEn: "Do even the smallest good deed, for you never know which one will lead you to heaven.",
    author: "Imam Hasan Al-Basri",
    category: "Semangat",
  ),
  Quote(
    text: "Keberhasilan bukan milik orang pintar, tapi milik mereka yang senantiasa berusaha.",
    textEn: "Success doesn't belong to the smart, but to those who consistently strive.",
    author: "B.J. Habibie",
    category: "Semangat",
  ),
  Quote(
    text: "Matahari selalu terbit, begitu juga dengan harapan baru.",
    textEn: "The sun always rises, and with it, new hope.",
    author: "Anonim",
    category: "Semangat",
  ),
  Quote(
    text: "Tindakan adalah kunci dasar untuk semua kesuksesan.",
    textEn: "Action is the foundational key to all success.",
    author: "Pablo Picasso",
    category: "Semangat",
  ),
  Quote(
    text: "Allah tidak akan mengubah nasib suatu kaum, hingga mereka mengubah keadaan diri mereka sendiri.",
    textEn: "Indeed, Allah will not change the condition of a people until they change what is in themselves.",
    author: "QS. Ar-Ra'd: 11",
    category: "Semangat",
  ),
];