import '../models_daily_free/quote_model.dart';

List<Quote> cintaQuotes = [
  Quote(
    text: "Cinta bukan tentang mencari seseorang yang sempurna, tapi menemukan seseorang yang membuat ketidaksempurnaanmu terasa sempurna.",
    textEn: "Love is not about finding a perfect person, but finding someone who makes your imperfections feel perfect.",
    author: "Sam Keen",
    category: "Cinta",
  ),
  Quote(
    text: "Dicintai secara mendalam oleh seseorang memberimu kekuatan, sementara mencintai seseorang secara mendalam memberimu keberanian.",
    textEn: "Being deeply loved by someone gives you strength, while loving someone deeply gives you courage.",
    author: "Lao Tzu",
    category: "Cinta",
  ),
  Quote(
    text: "Cinta sejati bukan berarti tidak terpisahkan. Itu berarti dipisahkan namun tidak ada yang berubah.",
    textEn: "True love doesn't mean being inseparable. It means being separated and nothing changes.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Mencintai seseorang memberikan kita kekuatan, dicintai seseorang memberikan kita keberanian.",
    textEn: "Loving someone gives us strength; being loved by someone gives us courage.",
    author: "Lao Tzu",
    category: "Cinta",
  ),
  Quote(
    text: "Cinta bukanlah tentang seberapa lama kamu mengenal seseorang, tapi tentang seseorang yang membuatmu tersenyum sejak kamu mengenalnya.",
    textEn: "Love is not about how long you've known someone, but about the one who has made you smile since the moment you met.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Tak ada yang lebih indah dari dua orang yang saling mendoakan dalam diam, namun Allah menyatukan hati mereka dalam terang.",
    textEn: "Nothing is more beautiful than two people praying for each other in silence, yet Allah unites their hearts in the light.",
    author: "Habiburrahman El Shirazy",
    category: "Cinta",
  ),
  Quote(
    text: "Cinta itu adalah ketika kebahagiaan orang lain lebih penting daripada kebahagiaanmu sendiri.",
    textEn: "Love is when the other person's happiness is more important than your own.",
    author: "H. Jackson Brown Jr.",
    category: "Cinta",
  ),
  Quote(
    text: "Cinta tak perlu pengorbanan, cinta hanya butuh perjuangan. Karena cinta tak akan pernah merasa berkorban.",
    textEn: "Love needs no sacrifice, it only needs struggle. For love will never feel like it is sacrificing.",
    author: "Sujiwo Tejo",
    category: "Cinta",
  ),
  Quote(
    text: "Cinta yang halal itu dimulai dari mata, turun ke hati, dan dibuktikan dengan janji suci.",
    textEn: "Pure love begins in the eyes, descends to the heart, and is proven through a sacred vow.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Jika aku tahu apa itu cinta, itu karena kamu.",
    textEn: "If I know what love is, it is because of you.",
    author: "Hermann Hesse",
    category: "Cinta",
  ),
  Quote(
    text: "Puncak kangen paling dahsyat adalah ketika dua orang tak saling telepon, SMS, BBM, tapi keduanya diam-diam saling mendoakan.",
    textEn: "The highest peak of longing is when two people don't call or message each other, but both secretly pray for one another.",
    author: "Sujiwo Tejo",
    category: "Cinta",
  ),
  Quote(
    text: "Cinta bukan melemahkan hati, bukan membawa putus asa, bukan menimbulkan tangis sedu sedan. Tetapi cinta menghidupkan pengharapan, menguatkan hati dalam perjuangan menempuh onak dan duri penghidupan.",
    textEn: "Love does not weaken the heart, nor does it bring despair or endless tears. Instead, love awakens hope and strengthens the heart to fight through the thorns of life.",
    author: "Buya Hamka",
    category: "Cinta",
  ),
  Quote(
    text: "Aku mencintaimu bukan karena siapa kamu, tapi karena siapa aku saat aku bersamamu.",
    textEn: "I love you not because of who you are, but because of who I am when I am with you.",
    author: "Roy Croft",
    category: "Cinta",
  ),
  Quote(
    text: "Cinta terbaik adalah jenis yang membangkitkan jiwa dan membuat kita menjangkau lebih banyak, yang menanamkan api di hati kita dan membawa kedamaian dalam pikiran kita.",
    textEn: "The best love is the kind that awakens the soul and makes us reach for more, that plants a fire in our hearts and brings peace to our minds.",
    author: "Nicholas Sparks",
    category: "Cinta",
  ),
  Quote(
    text: "Bahagia itu sederhana, cukup melihat orang yang kita sayangi tersenyum bahagia.",
    textEn: "Happiness is simple: just seeing the person we love smile with joy.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Cinta sejati tidak berakhir dengan kematian. Jika Allah menghendaki, cinta itu akan berlanjut sampai ke surga.",
    textEn: "True love does not end with death. If Allah wills, that love will continue into heaven.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Mencintai itu kata kerja. Maka perlu ada tindakan, pengorbanan, dan kesabaran.",
    textEn: "Love is a verb. Therefore, it requires action, sacrifice, and patience.",
    author: "Salim A. Fillah",
    category: "Cinta",
  ),
  Quote(
    text: "Ketika kamu menyadari bahwa kamu ingin menghabiskan sisa hidupmu dengan seseorang, kamu ingin sisa hidupmu dimulai sesegera mungkin.",
    textEn: "When you realize you want to spend the rest of your life with somebody, you want the rest of your life to start as soon as possible.",
    author: "Nora Ephron",
    category: "Cinta",
  ),
  Quote(
    text: "Cinta adalah ketika kamu melihat ke dalam mata seseorang dan melihat segalanya yang kamu butuhkan.",
    textEn: "Love is when you look into someone's eyes and see everything you need.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Jangan mencintai orang yang tidak mencintai Allah. Jika Allah saja dia tinggalkan, apalagi kamu.",
    textEn: "Do not love those who do not love Allah. If they can leave Allah, they can certainly leave you.",
    author: "Imam Syafi'i",
    category: "Cinta",
  ),
  Quote(
    text: "Satu-satunya cara untuk mendapatkan cinta adalah jangan menuntutnya, melainkan mulailah memberi cinta.",
    textEn: "The only way to receive love is to stop demanding it and start giving it.",
    author: "Dale Carnegie",
    category: "Cinta",
  ),
  Quote(
    text: "Rumah bukan hanya tempat berteduh, tapi sepasang tangan yang siap memelukmu saat kau lelah. Dan bagiku, itu kamu.",
    textEn: "Home is not just a shelter, but a pair of arms ready to embrace you when you're weary. And for me, that is you.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Cinta itu menjaga. Tergesa-gesa itu nafsu. Maka, sabarlah dalam menanti waktu yang tepat.",
    textEn: "Love is about protecting. Haste is lust. So, be patient in waiting for the right time.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Kamu adalah doa yang selalu aku semogakan.",
    textEn: "You are the prayer I always hope for.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Cinta tidak terdiri dari saling memandang, tetapi melihat bersama ke arah yang sama.",
    textEn: "Love does not consist in gazing at each other, but in looking outward together in the same direction.",
    author: "Antoine de Saint-Exup�ry",
    category: "Cinta",
  ),
  Quote(
    text: "Jika cinta itu ilmu, maka pengabdian adalah rumusnya, dan kesetiaan adalah hasilnya.",
    textEn: "If love were a science, then devotion would be its formula, and loyalty would be its result.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Cinta adalah perbuatan. Kata-kata dan tulisan indah adalah omong kosong tanpa wujud nyata.",
    textEn: "Love is an action. Beautiful words and writings are nonsense without real manifestation.",
    author: "Tere Liye",
    category: "Cinta",
  ),
  Quote(
    text: "Perempuan itu untuk dicintai, bukan untuk dimengerti sepenuhnya. Cintai saja, itu sudah cukup membuatnya bahagia.",
    textEn: "Women are meant to be loved, not fully understood. Just love them; that is enough to make them happy.",
    author: "Oscar Wilde",
    category: "Cinta",
  ),
  Quote(
    text: "Pasangan paling bahagia di dunia ini tidak pernah memiliki sifat yang sama. Mereka hanya saling memahami dengan baik tentang perbedaan yang mereka miliki.",
    textEn: "The happiest couples in the world never have the same nature. They simply understand each other's differences well.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Aku ingin mencintaimu dengan sederhana. Dengan kata yang tak sempat diucapkan kayu kepada api yang menjadikannya abu.",
    textEn: "I want to love you simply. Like words unspoken by wood to the fire that turns it to ash.",
    author: "Sapardi Djoko Damono",
    category: "Cinta",
  ),
  Quote(
    text: "Cinta itu bukan tentang menang atau kalah, tapi tentang tumbuh bersama.",
    textEn: "Love is not about winning or losing, but about growing together.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Kado terbaik yang bisa kamu berikan kepada seseorang adalah waktumu. Karena saat kamu memberikan waktu, kamu memberikan sebagian hidupmu yang tak bisa kembali.",
    textEn: "The best gift you can give to someone is your time. Because when you give your time, you are giving a portion of your life that can never be returned.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Jarak itu tidak berarti apa-apa saat seseorang berarti segalanya.",
    textEn: "Distance means nothing when someone means everything.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Dalam diamku, aku mencintaimu dengan doa yang paling kencang.",
    textEn: "In my silence, I love you with the loudest of prayers.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Cinta sejati itu memandang kelemahan lalu diubah menjadi kelebihan untuk saling melengkapi.",
    textEn: "True love looks at weaknesses and turns them into strengths to complement each other.",
    author: "B.J. Habibie",
    category: "Cinta",
  ),
  Quote(
    text: "Tak perlu seseorang yang sempurna, cukup seseorang yang memperlakukanmu sebagai prioritas dan tak pernah membiarkanmu merasa sendirian.",
    textEn: "You don't need someone perfect; just someone who treats you as a priority and never lets you feel alone.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Cinta adalah ketika kekuranganmu tidak lagi menjadi masalah baginya, tetapi menjadi alasan baginya untuk melengkapimu.",
    textEn: "Love is when your flaws are no longer an issue, but a reason for them to complete you.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Aku memilihmu. Dan aku akan memilihmu terus-menerus. Tanpa henti, tanpa ragu, dalam setiap detak jantungku.",
    textEn: "I choose you. And I will choose you over and over. Without pause, without doubt, in every single heartbeat.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Setia adalah kesopanan dari mereka yang mencintai. Hanya orang berkelas yang bisa memegang janji.",
    textEn: "Loyalty is the courtesy of those who love. Only a person of class can keep their promise.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Menikah itu nasib, mencintai itu takdir. Kamu bisa berencana menikah dengan siapa, tapi tak bisa rencanakan cintamu untuk siapa.",
    textEn: "Marriage is fate, but loving is destiny. You can plan who to marry, but you cannot plan who your heart falls for.",
    author: "Sujiwo Tejo",
    category: "Cinta",
  ),
  Quote(
    text: "Cinta bukan tentang memiliki. Cinta adalah tentang menghargai.",
    textEn: "Love is not about possession. Love is about appreciation.",
    author: "Kahlil Gibran",
    category: "Cinta",
  ),
  Quote(
    text: "Mencintai adalah belajar mendengarkan suara hati yang tak terucap.",
    textEn: "To love is to learn to listen to the unspoken voice of the heart.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Ketulusan cinta hanya bisa dirasakan oleh hati yang ikhlas menerima.",
    textEn: "The sincerity of love can only be felt by a heart that accepts with grace.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Bersamamu, aku belajar bahwa bahagia itu sederhana. Cukup ada kamu, dan waktu berhenti sejenak.",
    textEn: "With you, I learned that happiness is simple. Just you being there, and time stops for a moment.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Cinta yang baik adalah yang mendekatkanmu kepada Tuhan, bukan yang menjauhkanmu dari kewajiban.",
    textEn: "A good love is one that brings you closer to God, not one that pulls you away from your duties.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Aku mencintaimu, itu sebabnya aku takkan pernah selesai mendoakan keselamatanmu.",
    textEn: "I love you, and that is why I will never stop praying for your well-being.",
    author: "Sapardi Djoko Damono",
    category: "Cinta",
  ),
  Quote(
    text: "Tanda cinta yang tulus adalah pengampunan yang tak terbatas dan kesabaran yang tak berujung.",
    textEn: "The mark of sincere love is infinite forgiveness and endless patience.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Bukan kemewahan yang membuat cinta bertahan, tapi rasa syukur dan saling pengertian.",
    textEn: "It is not luxury that makes love last, but gratitude and mutual understanding.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Sejauh apapun kaki melangkah, hati tahu ke mana ia harus pulang. Kamu adalah rumahku.",
    textEn: "No matter how far my feet wander, my heart knows where to return. You are my home.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Cinta adalah kondisi di mana kebahagiaan orang lain sangat penting bagi kebahagiaanmu sendiri.",
    textEn: "Love is that condition in which the happiness of another person is essential to your own.",
    author: "Robert A. Heinlein",
    category: "Cinta",
  ),
  Quote(
    text: "Di antara miliaran manusia di bumi, Allah memilihmu untuk melengkapi separuh agamaku.",
    textEn: "Among the billions of humans on earth, Allah chose you to complete half of my faith.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Terima kasih telah menjadi alasan bagiku untuk tersenyum hari ini dan setiap hari.",
    textEn: "Thank you for being the reason I smile today and every day.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Pecinta sejati tidak akan pernah bertemu di suatu tempat. Mereka sudah saling mengisi satu sama lain sejak awal.",
    textEn: "Lovers don't finally meet somewhere. They're in each other all along.",
    author: "Jalaluddin Rumi",
    category: "Cinta",
  ),
  Quote(
    text: "Aku ingin berdua denganmu selamanya. Bukan karena aku takut sendirian, tapi karena duniaku lebih indah saat ada kamu.",
    textEn: "I want to be with you forever. Not because I'm afraid of being alone, but because my world is more beautiful with you in it.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Cinta bukanlah tentang menatap satu sama lain, tetapi menatap masa depan ke arah yang sama.",
    textEn: "Love does not consist in gazing at each other, but in looking together in the same direction toward the future.",
    author: "Antoine de Saint-Exup�ry",
    category: "Cinta",
  ),
  Quote(
    text: "Mencintai seseorang berarti melihat keajaiban yang tidak bisa dilihat oleh orang lain.",
    textEn: "To love someone means to see a miracle invisible to others.",
    author: "Fran�ois Mauriac",
    category: "Cinta",
  ),
  Quote(
    text: "Sehebat apapun kita merencanakan, rencana Allah yang menyatukan kita adalah yang paling indah.",
    textEn: "No matter how great our plans are, Allah's plan to unite us is the most beautiful.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Cinta itu sederhana. Aku untukmu, dan kamu untukku. Jika tak mampu menjadi pelengkap, setidaknya jangan jadi penggenap derita.",
    textEn: "Love is simple: I am for you, and you are for me. If you cannot be a complement, at least do not be a source of sorrow.",
    author: "Fiersa Besari",
    category: "Cinta",
  ),
  Quote(
    text: "Hal paling membahagiakan dalam hidup adalah keyakinan bahwa kita dicintai; dicintai karena diri kita sendiri, atau lebih tepatnya, dicintai terlepas dari kekurangan kita.",
    textEn: "The greatest happiness of life is the conviction that we are loved; loved for ourselves, or rather, loved in spite of ourselves.",
    author: "Victor Hugo",
    category: "Cinta",
  ),
  Quote(
    text: "Aku tidak menjanjikan hari-hari tanpa kesedihan, tapi aku berjanji akan selalu ada untuk memelukmu melewatinya.",
    textEn: "I don't promise days without sorrow, but I promise I will always be there to hold you through them.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Cinta adalah perbuatan. Cinta adalah kenyataan. Cinta bukan sekadar kata-kata indah yang terucap di bibir.",
    textEn: "Love is a deed. Love is a reality. Love is not just beautiful words spoken on the lips.",
    author: "Tere Liye",
    category: "Cinta",
  ),
  Quote(
    text: "Jodoh itu bukan seberapa dekat kamu dengannya, tapi seberapa yakin Allah menjodohkanmu dengannya.",
    textEn: "Soulmates aren't about how close you are to them, but how certain Allah is about uniting you with them.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Jika kamu hidup sampai seratus tahun, aku ingin hidup seratus tahun kurang satu hari, jadi aku tidak perlu hidup tanpamu.",
    textEn: "If you live to be a hundred, I want to live to be a hundred minus one day so I never have to live without you.",
    author: "A.A. Milne",
    category: "Cinta",
  ),
  Quote(
    text: "Mencintai itu tidak harus memiliki, tapi menjaga. Menjaga nama baiknya, menjaga kehormatannya, dan menjaga rahasianya.",
    textEn: "To love is not necessarily to possess, but to protect. Protecting their reputation, their honor, and their secrets.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Kamu adalah notifikasi favorit di setiap pagi dan doa penutup di setiap malamku.",
    textEn: "You are my favorite notification every morning and my closing prayer every night.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Cinta itu laksana angin. Kau tidak bisa melihatnya, tapi kau bisa merasakannya.",
    textEn: "Love is like the wind. You can't see it, but you can feel it.",
    author: "Nicholas Sparks",
    category: "Cinta",
  ),
  Quote(
    text: "Bukan karena aku butuh, maka aku mencintaimu. Tapi karena aku mencintaimu, maka aku butuh kamu.",
    textEn: "I love you not because I need you, but I need you because I love you.",
    author: "Erich Fromm",
    category: "Cinta",
  ),
  Quote(
    text: "Pasangan yang baik adalah yang mau diajak berdiskusi, bukan yang memaksakan kehendak sendiri.",
    textEn: "A good partner is one willing to discuss, not one who imposes their own will.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Setiap kali aku melihatmu, aku jatuh cinta lagi.",
    textEn: "Every time I look at you, I fall in love all over again.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Tulang rusuk tidak akan pernah tertukar. Pemiliknya akan datang pada saat yang tepat, dengan cara yang tepat.",
    textEn: "A rib will never be misplaced. Its owner will come at the right time, in the right way.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Jangan rindu. Ini berat. Kau tak akan kuat. Biar aku saja.",
    textEn: "Don't miss me. It's heavy. You won't be strong enough. Let it be me.",
    author: "Pidi Baiq",
    category: "Cinta",
  ),
  Quote(
    text: "Cinta yang dewasa tidak menyimpan dendam, ia hanya menyimpan rindu dan pengertian.",
    textEn: "Mature love holds no grudges; it only holds longing and understanding.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Bahasa cinta terbaik adalah ketulusan doa. Tak terdengar telinga, tapi tembus ke langit.",
    textEn: "The best love language is the sincerity of prayer. Unheard by ears, yet piercing through the heavens.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Aku mencintaimu tanpa tahu bagaimana, kapan, atau dari mana. Aku mencintaimu secara sederhana, tanpa masalah atau kebanggaan.",
    textEn: "I love you without knowing how, or when, or from where. I love you simply, without problems or pride.",
    author: "Pablo Neruda",
    category: "Cinta",
  ),
  Quote(
    text: "Hubungan yang indah adalah ketika dua orang bisa menjadi sahabat, kekasih, dan teman berbagi mimpi sekaligus.",
    textEn: "A beautiful relationship is when two people can be best friends, lovers, and dream-sharers all at once.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Bunga tidak bisa mekar tanpa sinar matahari, dan manusia tidak bisa hidup tanpa cinta.",
    textEn: "A flower cannot blossom without sunshine, and man cannot live without love.",
    author: "Max Muller",
    category: "Cinta",
  ),
  Quote(
    text: "Seseorang yang benar-benar mencintaimu akan melihat betapa berantakannya kamu, betapa murungnya kamu, namun tetap ingin berada di sisimu.",
    textEn: "Someone who truly loves you will see how messy you are, how moody you can be, yet still choose to stay by your side.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Cinta bukan hanya tentang menemukan tangan yang tepat untuk digenggam, tetapi menemukan hati yang tepat untuk bersandar.",
    textEn: "Love is not just about finding the right hand to hold, but finding the right heart to lean on.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Ketika aku bersamamu, waktu terasa berhenti. Dan ketika tanpamu, waktu terasa begitu lambat.",
    textEn: "When I am with you, time feels like it stops. And without you, time feels so slow.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Bukti cinta terbesar adalah kesetiaan saat jauh dan perhatian saat dekat.",
    textEn: "The greatest proof of love is loyalty when far and attention when near.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Cinta itu menyembuhkan. Ia menyembuhkan mereka yang memberikannya maupun mereka yang menerimanya.",
    textEn: "Love is the great cure. It heals both those who give it and those who receive it.",
    author: "Dr. Karl Menninger",
    category: "Cinta",
  ),
  Quote(
    text: "Jatuh cinta padamu adalah hal termudah yang pernah kulakukan dalam hidupku.",
    textEn: "Falling in love with you was the easiest thing I've ever done in my life.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Pasangan sejati adalah dia yang mendekatkanmu kepada Tuhan, bukan yang membuatmu lupa pada-Nya.",
    textEn: "A true partner is one who brings you closer to God, not one who makes you forget Him.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Dalam matematika cinta, satu tambah satu sama dengan segalanya, dan dua kurang satu sama dengan tidak ada.",
    textEn: "In the arithmetic of love, one plus one equals everything, and two minus one equals nothing.",
    author: "Mignon McLaughlin",
    category: "Cinta",
  ),
  Quote(
    text: "Cinta tidak menuntut kesempurnaan, tapi cinta akan memahami setiap kelemahan.",
    textEn: "Love does not demand perfection, but love will understand every weakness.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Aku ingin menjadi alasan di balik senyum manismu setiap hari.",
    textEn: "I want to be the reason behind your sweet smile every day.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Cinta itu seperti menanam pohon. Jika kamu sabar merawatnya, ia akan memberimu keteduhan.",
    textEn: "Love is like planting a tree. If you are patient in nurturing it, it will provide you with shade.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Orang yang tulus mencintaimu tidak akan menjanjikan bintang dan bulan, tapi dia akan berjanji untuk tidak pergi saat badai datang.",
    textEn: "A person who truly loves you won't promise the moon and stars, but they will promise not to leave when the storm comes.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Di mana ada cinta yang besar, di sana selalu ada keajaiban.",
    textEn: "Where there is great love, there are always miracles.",
    author: "Willa Cather",
    category: "Cinta",
  ),
  Quote(
    text: "Terima kasih telah menerima segala kurangku dan menjadikannya cukup.",
    textEn: "Thank you for accepting all my shortcomings and making them enough.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Cinta sejati itu seperti rumah; tempat kamu kembali, bukan tempat kamu singgah.",
    textEn: "True love is like a home; a place you return to, not just a place you stay.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Ketidaksempurnaanmu adalah hal yang membuatmu sempurna di mataku.",
    textEn: "Your imperfections are what make you perfect in my eyes.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Kita tidak jatuh cinta pada orang yang sempurna, tapi kita menyempurnakan cinta dengan melihat ketidaksempurnaan orang itu secara sempurna.",
    textEn: "We don't fall in love with perfect people, but we perfect our love by seeing an imperfect person perfectly.",
    author: "Sam Keen",
    category: "Cinta",
  ),
  Quote(
    text: "Mencintai bukan berarti mengekang. Mencintai adalah membebaskan pasangan untuk berkembang menjadi versi terbaik dirinya.",
    textEn: "To love is not to restrain. To love is to free your partner to grow into the best version of themselves.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Duduklah bersamaku, akan kuceritakan betapa indahnya hidup sejak kau ada.",
    textEn: "Sit with me; I will tell you how beautiful life has been since you've been here.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Tuhan menciptakan jarak agar kita mengerti indahnya pertemuan dan mahalnya kesetiaan.",
    textEn: "God created distance so that we understand the beauty of meeting and the value of loyalty.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Bagiku, definisi rumah bukanlah bangunan, melainkan di mana pun aku bersamamu.",
    textEn: "To me, the definition of home is not a building, but wherever I am with you.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Harta yang paling berharga bagi seorang pria di dunia ini adalah hati seorang wanita yang penuh kasih sayang.",
    textEn: "The most valuable asset for a man in this world is the heart of a loving woman.",
    author: "Josiah G. Holland",
    category: "Cinta",
  ),
  Quote(
    text: "Cinta yang suci adalah yang membawamu pada ketaatan, bukan kemaksiatan.",
    textEn: "A pure love is one that leads you to obedience, not disobedience.",
    author: "Unknown",
    category: "Cinta",
  ),
  Quote(
    text: "Kamu adalah satu-satunya orang yang ingin aku ganggu seumur hidupku.",
    textEn: "You are the only person I want to annoy for the rest of my life.",
    author: "Unknown",
    category: "Cinta",
  ),
];