import '../models_daily_free/quote_model.dart';

List<Quote> syukurQuotes = [
  Quote(
    text: "Bukan kebahagiaan yang membuat kita bersyukur, tapi rasa syukurlah yang membuat kita bahagia.",
    textEn: "It is not happiness that makes us grateful, but gratitude that makes us happy.",
    author: "Anonim",
    category: "Syukur",
  ),
  Quote(
    text: "Lihatlah ke bawah untuk urusan dunia agar kamu bersyukur, dan lihatlah ke atas untuk urusan akhirat agar kamu terpacu.",
    textEn: "Look at those who are beneath you in worldly matters so that you may be grateful, and look at those who are above you in spiritual matters so that you may be inspired.",
    author: "Hadist Riwayat Muslim",
    category: "Syukur",
  ),
  Quote(
    text: "Jika kamu tidak mampu mensyukuri yang sedikit, kamu tidak akan mampu mensyukuri yang banyak.",
    textEn: "He who is not grateful for the little things will not be grateful for the large things.",
    author: "HR. Ahmad",
    category: "Syukur",
  ),
  Quote(
    text: "Nikmat itu ibarat binatang liar, ikatlah ia dengan tali syukur agar tidak lepas dan lari darimu.",
    textEn: "Blessings are like wild animals; tether them with the rope of gratitude so they do not escape and run from you.",
    author: "Ali bin Abi Thalib",
    category: "Syukur",
  ),
  Quote(
    text: "Orang yang paling bersyukur adalah orang yang paling kaya jiwanya, meski sederhana hidupnya.",
    textEn: "The most grateful person is the one who is richest in soul, no matter how simple their life may be.",
    author: "Buya Hamka",
    category: "Syukur",
  ),
  Quote(
    text: "Syukur adalah kunci yang membuka gembok tambahan nikmat dari Tuhan.",
    textEn: "Gratitude is the key that opens the lock of increased blessings from the Lord.",
    author: "Rumi",
    category: "Syukur",
  ),
  Quote(
    text: "Jangan menghitung apa yang hilang, tapi hitunglah apa yang masih tersisa dan syukuri.",
    textEn: "Do not count what is lost, but count what remains and be grateful.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Kekayaan yang sejati bukanlah banyaknya harta, melainkan hati yang selalu merasa cukup (Qanaah).",
    textEn: "True wealth is not an abundance of possessions, but a heart that is always content.",
    author: "HR. Bukhari Muslim",
    category: "Syukur",
  ),
  Quote(
    text: "Bernafas tanpa rasa sakit adalah nikmat yang sering lupa kita syukuri setiap detiknya.",
    textEn: "Breathing without pain is a blessing we often forget to cherish every single second.",
    author: "Imam Syafi'i",
    category: "Syukur",
  ),
  Quote(
    text: "Syukur bukan hanya di lisan, tapi pengakuan di hati dan pembuktian lewat amal perbuatan.",
    textEn: "Gratitude is not only on the tongue, but an acknowledgment in the heart and proof through one's deeds.",
    author: "Ibnu Qayyim Al-Jauziyah",
    category: "Syukur",
  ),
  Quote(
    text: "Sesungguhnya jika kamu bersyukur, pasti Kami akan menambah (nikmat) kepadamu.",
    textEn: "If you are grateful, I will surely increase you [in favor].",
    author: "QS. Ibrahim: 7",
    category: "Syukur",
  ),
  Quote(
    text: "Tanda syukur yang tertinggi adalah ketika engkau tidak menggunakan nikmat-Nya untuk bermaksiat.",
    textEn: "The highest sign of gratitude is when you do not use His blessings to commit disobedience.",
    author: "Imam Al-Ghazali",
    category: "Syukur",
  ),
  Quote(
    text: "Semakin banyak kau bersyukur, semakin banyak alasan yang Tuhan berikan untukmu tersenyum.",
    textEn: "The more you are grateful, the more reasons God will give you to smile.",
    author: "Oprah Winfrey",
    category: "Syukur",
  ),
  Quote(
    text: "Jalan termudah untuk merasa tenang adalah berhenti mengeluh dan mulai mensyukuri hal-hal kecil.",
    textEn: "The easiest way to feel at peace is to stop complaining and start being grateful for the little things.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Seandainya kamu tahu bagaimana Allah mengatur urusanmu, hatimu pasti akan meleleh karena cinta dan syukur kepada-Nya.",
    textEn: "If you knew how Allah manages your affairs for you, your heart would melt out of love and gratitude for Him.",
    author: "Ibnu Qayyim",
    category: "Syukur",
  ),
  Quote(
    text: "Bersyukurlah atas masa-masa sulit, karena di situlah kamu tumbuh menjadi lebih kuat.",
    textEn: "Be grateful for the hard times, for it is there that you grow into someone stronger.",
    author: "Anonim",
    category: "Syukur",
  ),
  Quote(
    text: "Cukup adalah kata yang sederhana, tapi ia adalah puncak dari rasa syukur yang sesungguhnya.",
    textEn: " 'Enough' is a simple word, but it is the true peak of ultimate gratitude.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Rasa syukur mengubah apa yang kita miliki menjadi cukup, dan lebih dari cukup.",
    textEn: "Gratitude turns what we have into enough, and more than enough.",
    author: "Melody Beattie",
    category: "Syukur",
  ),
  Quote(
    text: "Jangan biarkan ambisimu untuk masa depan membuatmu lupa menikmati berkah hari ini.",
    textEn: "Don't let your ambition for the future make you forget to enjoy the blessings of today.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Dua hal yang jika engkau miliki akan menyelamatkanmu: Hati yang bersyukur dan lidah yang berdzikir.",
    textEn: "Two things that will save you if you possess them: a grateful heart and a tongue that remembers God.",
    author: "Ibnu Mas'ud",
    category: "Syukur",
  ),
  Quote(
    text: "Bahagia itu sederhana, ketika keinginanmu sejalan dengan apa yang sudah Allah berikan.",
    textEn: "Happiness is simple, when your desires align with what Allah has already given.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Orang yang pesimis mengeluh tentang angin, orang yang optimis berharap angin berubah, orang yang bersyukur mengatur layar.",
    textEn: "The pessimist complains about the wind; the optimist expects it to change; the grateful one adjusts the sails.",
    author: "William Arthur Ward",
    category: "Syukur",
  ),
  Quote(
    text: "Syukur adalah obat penawar hati yang gelisah karena keinginan duniawi.",
    textEn: "Gratitude is the antidote for a heart restless with worldly desires.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Ketika kamu bangun pagi ini, ingatlah betapa berharganya hak istimewa untuk hidup, bernapas, dan menikmati hari.",
    textEn: "When you arise in the morning, think of what a precious privilege it is to be alive�to breathe, to think, to enjoy, to love.",
    author: "Marcus Aurelius",
    category: "Syukur",
  ),
  Quote(
    text: "Allah tidak menjanjikan langit selalu biru, tapi Dia menjanjikan akan selalu menyertai hamba-Nya yang bersyukur.",
    textEn: "God did not promise that the sky would always be blue, but He promised to always accompany His grateful servants.",
    author: "Anonim",
    category: "Syukur",
  ),
  Quote(
    text: "Rezeki itu bukan hanya uang, tapi teman yang baik, anak yang sholeh, dan hati yang tenang adalah rezeki yang mahal.",
    textEn: "Provision is not just money; good friends, righteous children, and a peaceful heart are precious riches.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Jangan bandingkan prosesmu dengan orang lain, karena bunga tidak mekar di waktu yang bersamaan. Syukuri musimmu.",
    textEn: "Don't compare your journey to others, for flowers do not bloom at the same time. Cherish your season.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Seringkali kita terlalu sibuk melihat pintu yang tertutup, hingga lupa melihat jendela yang terbuka lebar.",
    textEn: "Often we are so busy looking at the closed door that we forget to see the window wide open.",
    author: "Helen Keller",
    category: "Syukur",
  ),
  Quote(
    text: "Bersyukur itu membebaskan diri dari penjara ketidakpuasan.",
    textEn: "Being grateful liberates oneself from the prison of dissatisfaction.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Jika satu-satunya doa yang kau ucapkan seumur hidupmu adalah 'Terima Kasih', itu sudah cukup.",
    textEn: "If the only prayer you ever say in your entire life is 'Thank you,' it will be enough.",
    author: "Meister Eckhart",
    category: "Syukur",
  ),
  Quote(
    text: "Barangsiapa yang tidak berterima kasih kepada manusia, dia tidak bersyukur kepada Allah.",
    textEn: "He who does not thank people, does not thank Allah.",
    author: "HR. Tirmidzi",
    category: "Syukur",
  ),
  Quote(
    text: "Musibah yang mendekatkanmu pada Allah lebih baik daripada nikmat yang membuatmu lupa bersyukur.",
    textEn: "A calamity that brings you closer to Allah is better than a blessing that makes you forget to be grateful.",
    author: "Ibnu Taimiyah",
    category: "Syukur",
  ),
  Quote(
    text: "Hati yang bersyukur adalah magnet bagi keajaiban-keajaiban tak terduga.",
    textEn: "A grateful heart is a magnet for unexpected miracles.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Syukur membuat masa lalu menjadi kenangan manis, hari ini menjadi kedamaian, dan esok menjadi harapan.",
    textEn: "Gratitude turns the past into sweet memories, today into peace, and tomorrow into hope.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Jangan merusak apa yang kau miliki hari ini dengan menginginkan apa yang belum tentu kau butuhkan.",
    textEn: "Do not spoil what you have today by desiring what you may not even need.",
    author: "Epicurus",
    category: "Syukur",
  ),
  Quote(
    text: "Hidup ini indah jika kita pandai bersyukur, namun terasa sempit jika kita hanya pandai mengukur.",
    textEn: "Life is beautiful when we are good at gratitude, but it feels narrow when we are only good at measuring.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Bersyukur mengajarkan kita bahwa kebahagiaan tidak bergantung pada apa yang kita dapat, tapi bagaimana kita melihat.",
    textEn: "Gratitude teaches us that happiness doesn't depend on what we get, but on how we see.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Tak ada orang miskin di dunia ini, kecuali mereka yang tidak punya rasa syukur di hatinya.",
    textEn: "There are no poor people in this world, except for those who have no sense of gratitude in their hearts.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Doa terbaik saat lelah adalah bersyukur karena masih diberi kekuatan untuk berusaha.",
    textEn: "The best prayer when exhausted is to be grateful for still being given the strength to strive.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Alhamdulillah untuk setiap 'Tidak' dari-Mu yang menyelamatkanku dari hal yang salah.",
    textEn: "Alhamdulillah for every 'No' from You that saved me from the wrong things.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Syukur adalah seni melihat keindahan di tengah ketidaksempurnaan hidup.",
    textEn: "Gratitude is the art of seeing beauty amidst life's imperfections.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Sabar ketika diuji, bersyukur ketika diberi. Itulah rumus hidup paling menenangkan.",
    textEn: "Patient when tested, grateful when given. That is the most calming formula for life.",
    author: "Umar bin Khattab",
    category: "Syukur",
  ),
  Quote(
    text: "Matahari tidak meminta bayaran untuk sinarnya. Belajarlah dari alam tentang memberi dan menerima dengan syukur.",
    textEn: "The sun does not ask for payment for its rays. Learn from nature about giving and receiving with gratitude.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Setiap detak jantungmu adalah hadiah yang tak bisa dibeli dengan uang. Syukurilah.",
    textEn: "Every beat of your heart is a gift that money cannot buy. Cherish it with gratitude.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Orang yang bersyukur tidak punya waktu untuk iri pada rezeki orang lain.",
    textEn: "Grateful people have no time to be envious of others' fortune.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Syukur itu menular. Mulailah dari dirimu, dan sekelilingmu akan merasakan kedamaiannya.",
    textEn: "Gratitude is contagious. Start with yourself, and those around you will feel its peace.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Langit tidak selalu cerah, tapi Tuhan selalu Maha Pemurah bagi hati yang berserah.",
    textEn: "The sky is not always bright, but God is always Gracious to a surrendered heart.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Kunci ketenangan adalah menerima apa yang terjadi dan mensyukuri apa yang dimiliki.",
    textEn: "The key to tranquility is accepting what happens and being grateful for what is possessed.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Jangan sampai kehilangan nikmat baru menyadarkanmu untuk bersyukur.",
    textEn: "Don't let the loss of a blessing be the only thing that makes you realize you should have been grateful.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Bersyukur adalah cara kita memeluk takdir Allah dengan senyuman.",
    textEn: "Gratitude is the way we embrace Allah's destiny with a smile.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Harta yang paling berharga adalah lisan yang senantiasa basah dengan syukur.",
    textEn: "The most valuable treasure is a tongue that is constantly wet with gratitude.",
    author: "Hasan Al-Basri",
    category: "Syukur",
  ),
  Quote(
    text: "Tuhan memberi kita 86.400 detik hari ini. Sudahkah kamu menggunakan satu detik untuk mengucap Alhamdulillah?",
    textEn: "God gave us 86,400 seconds today. Have you used even one second to say Alhamdulillah?",
    author: "William Arthur Ward",
    category: "Syukur",
  ),
  Quote(
    text: "Iman itu terbagi menjadi dua bagian: separuh dalam kesabaran dan separuh lagi dalam rasa syukur.",
    textEn: "Faith is divided into two halves: one half in patience and the other half in gratitude.",
    author: "Ibnu Qayyim",
    category: "Syukur",
  ),
  Quote(
    text: "Sungguh menakjubkan urusan orang mukmin. Jika diberi nikmat ia bersyukur, dan jika diuji ia bersabar.",
    textEn: "How wonderful is the affair of the believer! If prosperity comes to him, he is grateful; and if adversity comes to him, he is patient.",
    author: "HR. Muslim",
    category: "Syukur",
  ),
  Quote(
    text: "Kesehatan adalah mahkota di kepala orang sehat yang hanya bisa dilihat oleh orang sakit.",
    textEn: "Health is a crown on the heads of the healthy that only the sick can see.",
    author: "Pepatah Arab",
    category: "Syukur",
  ),
  Quote(
    text: "Syukur adalah jembatan yang menghubungkan keadaan 'tidak punya apa-apa' menjadi 'punya segalanya'.",
    textEn: "Gratitude is the bridge that connects the state of 'having nothing' to 'having everything'.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Mengeluh tidak akan memperbaiki keadaan, tapi bersyukur akan langsung memperbaiki suasana hati.",
    textEn: "Complaining won't improve the situation, but gratitude will instantly improve the mood.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Kadang Allah mematahkan hatimu hanya untuk menyelamatkan jiwamu. Bersyukurlah atas penyelamatan itu.",
    textEn: "Sometimes Allah breaks your heart just to save your soul. Be grateful for that rescue.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Jangan hanya bersyukur saat sampai di tujuan yang indah, tapi syukuri juga kaki yang kuat untuk melangkah ke sana.",
    textEn: "Don't just be grateful when you reach a beautiful destination, but also for the strong legs that walked you there.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Segelas air putih tak berarti bagi seorang raja, tapi segalanya bagi musafir yang kehausan di gurun. Syukuri hal sederhana.",
    textEn: "A glass of water means nothing to a king, but everything to a thirsty traveler in the desert. Appreciate the simple things.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Orang terkaya bukanlah yang memiliki paling banyak, tetapi yang membutuhkan paling sedikit.",
    textEn: "The richest person is not the one who has the most, but the one who needs the least.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Syukur adalah suara dari iman yang tenang.",
    textEn: "Gratitude is the voice of a calm faith.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Lihatlah tanganmu, itu adalah alat yang Allah titipkan untuk membangun jembatan ke surga melalui karya dan sedekah.",
    textEn: "Look at your hands; they are tools entrusted by Allah to build a bridge to heaven through work and charity.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Redamkan bisingnya keinginan duniawi yang tak ada habisnya dengan bisikan rasa syukur yang menyejukkan.",
    textEn: "Drown the noise of endless worldly desires with the soothing whisper of gratitude.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Jangan tunggu hari istimewa untuk bersyukur. Masih bisa bernafas hari ini adalah peristiwa yang sangat istimewa.",
    textEn: "Don't wait for a special day to be grateful. Being able to breathe today is a very special event.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Syukur adalah bunga terindah yang hanya bisa tumbuh subur di tanah kerendahan hati.",
    textEn: "Gratitude is the most beautiful flower that can only thrive in the soil of humility.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Jika ingin menemukan kebahagiaan yang hilang, cobalah cari di dalam 'kotak' rasa syukurmu.",
    textEn: "If you want to find lost happiness, try looking inside your 'box' of gratitude.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Rasa syukur mampu melukis senyuman bahkan di wajah masalah yang paling rumit sekalipun.",
    textEn: "Gratitude is able to paint a smile even on the face of the most complicated problems.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Syukur adalah mata uang langit yang berlaku di mana saja, belanjakanlah setiap hari agar rezekimu barokah.",
    textEn: "Gratitude is heaven's currency that is valid everywhere; spend it every day so your provision is blessed.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Hati yang tak bersyukur gersang seperti padang pasir, hati yang bersyukur rindang seperti taman surga.",
    textEn: "An ungrateful heart is parched like a desert; a grateful heart is lush like the gardens of paradise.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Syukur membuka pintu hikmah yang seringkali terkunci rapat oleh keluhan.",
    textEn: "Gratitude opens the doors of wisdom that are often locked tight by complaints.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Dengan kacamata syukur, setiap kejadian�baik atau buruk�terlihat sebagai bentuk kasih sayang Tuhan.",
    textEn: "Through the lens of gratitude, every event�good or bad�is seen as a form of God's love.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Bersyukur mengangkat beban emosi di pundak, membuat perjalanan hidup terasa jauh lebih ringan.",
    textEn: "Being grateful lifts the emotional burden off the shoulders, making the journey of life feel much lighter.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Pikiran yang dipenuhi rasa syukur adalah magnet yang menarik hal-hal besar untuk mendekat.",
    textEn: "A mind filled with gratitude is a magnet that attracts great things to draw near.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Ketakutan akan masa depan akan hilang seketika saat rasa syukur atas hari ini datang.",
    textEn: "Fear of the future vanishes instantly when gratitude for today arrives.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Syukur adalah kekayaan yang sebenarnya, sedangkan keluhan adalah awal dari kemiskinan mental.",
    textEn: "Gratitude is true wealth, while complaining is the beginning of mental poverty.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Perjuangan batin melawan gelisah akan berakhir tepat saat rasa syukur dimulai.",
    textEn: "The inner struggle against anxiety will end exactly when gratitude begins.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Syukur adalah air penyejuk bagi jiwa yang kepanasan oleh api ambisi.",
    textEn: "Gratitude is cooling water for a soul heated by the fire of ambition.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Selalu ada hal untuk disyukuri, bahkan di hari yang menurutmu paling buruk sekalipun.",
    textEn: "There is always something to be grateful for, even on what you think is your worst day.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Syukur adalah vitamin terbaik untuk meningkatkan imun tubuh dan ketahanan jiwa.",
    textEn: "Gratitude is the best vitamin to boost physical immunity and spiritual resilience.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Awali hari dengan niat baik dan hati yang penuh syukur, maka semesta akan mendukung langkahmu.",
    textEn: "Start the day with good intentions and a grateful heart, and the universe will support your steps.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Syukur adalah pintu gerbang utama menuju kelimpahan rezeki yang tak disangka-sangka.",
    textEn: "Gratitude is the main gateway to an unexpected abundance of provision.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Saat ombak kekecewaan menghantam, jadilah karang syukur yang teguh dan tak tergoyahkan.",
    textEn: "When waves of disappointment strike, be a steady and unshakable rock of gratitude.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Ada dua cara menjalani hidup: menganggap tidak ada keajaiban, atau menganggap segala sesuatu adalah keajaiban.",
    textEn: "There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.",
    author: "Albert Einstein",
    category: "Syukur",
  ),
  Quote(
    text: "Berbahagialah mereka yang bisa melihat keindahan di tempat-tempat sederhana di mana orang lain tidak melihat apa-apa.",
    textEn: "Blessed are they who see beautiful things in humble places where other people see nothing.",
    author: "Camille Pissarro",
    category: "Syukur",
  ),
  Quote(
    text: "Syukur adalah emosi manusia yang paling menyehatkan, lebih ampuh dari obat penenang manapun.",
    textEn: "Gratitude is the healthiest of all human emotions, more potent than any tranquilizer.",
    author: "Hans Selye",
    category: "Syukur",
  ),
  Quote(
    text: "Satu momen syukur yang tulus bisa mengubah energi satu hari penuh menjadi berkah.",
    textEn: "One moment of sincere gratitude can transform the energy of an entire day into a blessing.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Syukur adalah bentuk sopan santun tertinggi seorang hamba kepada Sang Pencipta.",
    textEn: "Gratitude is a servant's highest form of courtesy toward the Creator.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Merasa bersyukur tapi tidak mengungkapkannya ibarat membungkus kado indah tapi tidak pernah memberikannya.",
    textEn: "Feeling gratitude and not expressing it is like wrapping a present and not giving it.",
    author: "William Arthur Ward",
    category: "Syukur",
  ),
  Quote(
    text: "Syukur membuat kita tumbuh dewasa dan meluaskan kapasitas hati untuk menerima lebih banyak nikmat.",
    textEn: "Gratitude makes us grow up and expands the heart's capacity to receive more blessings.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Hidup dengan syukur adalah hidup dengan mental kemenangan, bukan mental korban.",
    textEn: "Living with gratitude is living with a winning mentality, not a victim mentality.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Jangan biarkan terik matahari membuatmu mengeluh, hingga lupa bersyukur akan adanya tempat berteduh.",
    textEn: "Don't let the scorching sun make you complain until you forget to be grateful for the existence of shelter.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Syukur menjadikanmu penikmat hidup sejati, bukan sekadar penonton yang iri hati.",
    textEn: "Gratitude makes you a true enjoyer of life, not just an envious spectator.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Setiap kesulitan membawa benih kemudahan di dalamnya, siramilah dengan syukur agar benih itu tumbuh.",
    textEn: "Every adversity carries with it the seed of an equivalent benefit; water it with gratitude so that seed may grow.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Nikmat paling tenang adalah bisa tidur nyenyak di malam hari tanpa beban dendam. Syukurilah.",
    textEn: "The most peaceful blessing is being able to sleep soundly at night without the burden of a grudge. Cherish it.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Hujan bukan penghalang rezeki, ia adalah rahmat bagi bumi yang haus. Begitu juga ujian bagi jiwa.",
    textEn: "Rain is not a barrier to fortune; it is a mercy for the thirsty earth. So too are trials for the soul.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Keluarga yang rukun adalah surga yang disegerakan di dunia. Syukuri keberadaan mereka sebelum tiada.",
    textEn: "A harmonious family is a heaven hastened on earth. Cherish their presence before they are gone.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Mampu menggerakkan tubuh untuk beribadah hari ini adalah taufik yang mahal, jangan lupa bersyukur.",
    textEn: "Being able to move your body for worship today is a precious guidance; do not forget to be grateful.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Syukur bukanlah tentang seberapa tebal dompetmu, tapi seberapa lapang hatimu.",
    textEn: "Gratitude is not about how thick your wallet is, but how wide your heart is.",
    author: "Original",
    category: "Syukur",
  ),
  Quote(
    text: "Tuhan tidak pernah terlambat dan tidak pernah terlalu cepat. Rencana-Nya sempurna bagi hamba yang bersyukur.",
    textEn: "God is never late and never too early. His plan is perfect for those who are grateful.",
    author: "Original",
    category: "Syukur",
  ),
];