import '../models_daily_free/quote_model.dart';

List<Quote> galauQuotes = [
  Quote(
    text: "Luka yang tak terlihat adalah yang paling sulit untuk disembuhkan, namun ia mengajarkan kita cara bertahan.",
    textEn: "The wounds that are invisible are the hardest to heal, yet they teach us how to endure.",
    author: "Anonim",
    category: "Galau",
  ),
  Quote(
    text: "Terkadang melepaskan bukan berarti kamu berhenti peduli, tapi kamu sadar bahwa orang yang kamu pertahankan tidak peduli.",
    textEn: "Sometimes letting go doesn't mean you stop caring, but you realize that the person you're holding onto doesn't care.",
    author: "Anonim",
    category: "Galau",
  ),
  Quote(
    text: "Terkadang, cara terbaik untuk mencintai adalah mendoakan dari kejauhan, karena doa adalah pelukan yang tak tersentuh tangan namun sampai ke hati.",
    textEn: "Sometimes, the best way to love is to pray from afar, for prayer is an embrace untouched by hands that reaches the heart.",
    author: "Anonim",
    category: "Galau",
  ),
  Quote(
    text: "Bukan melepaskan yang membuatmu sakit, tapi memegang erat sesuatu yang ingin pergi.",
    textEn: "It is not letting go that hurts you, but holding on tightly to something that wants to leave.",
    author: "Fiersa Besari (Diadaptasi)",
    category: "Galau",
  ),
  Quote(
    text: "Allah memisahkanmu darinya mungkin karena Dia mendengar percakapan yang tidak kamu dengar, dan melihat hal yang tidak kamu lihat.",
    textEn: "Allah separated you from them perhaps because He heard conversations you didn't hear and saw things you didn't see.",
    author: "Islamic Quotes",
    category: "Galau",
  ),
  Quote(
    text: "Hujan turun bukan untuk menghapus kenangan, tapi untuk menyamarkan air mata yang tak sanggup kau jelaskan.",
    textEn: "The rain falls not to wash away memories, but to disguise the tears you cannot explain.",
    author: "Original",
    category: "Galau",
  ),
  Quote(
    text: "Sakit hati adalah cara Tuhan mengajarkan bahwa berharap kepada manusia adalah seni mematahkan hati sendiri.",
    textEn: "Heartbreak is God's way of teaching that placing hope in humans is the art of breaking your own heart.",
    author: "Habib Ali Al-Jufri",
    category: "Galau",
  ),
  Quote(
    text: "Ada rindu yang tidak pernah habis, meski temu tak pernah terwujud.",
    textEn: "There is a longing that never ends, even though a meeting never manifests.",
    author: "Tere Liye",
    category: "Galau",
  ),
  Quote(
    text: "Diam adalah jeritan paling keras dari hati yang sudah terlalu lelah untuk berharap.",
    textEn: "Silence is the loudest scream from a heart that is far too tired to hope.",
    author: "Original",
    category: "Galau",
  ),
  Quote(
    text: "Jika dia memang takdirmu, sejauh apapun dia pergi, Allah akan menuntunnya kembali. Jika bukan, sedekat apapun dia, pasti akan berjarak.",
    textEn: "If they are your destiny, no matter how far they go, Allah will lead them back. If not, no matter how close they are, there will always be a distance.",
    author: "Nasehat Lama",
    category: "Galau",
  ),
  Quote(
    text: "Melupakanmu seperti mencoba mengingat seseorang yang belum pernah aku temui, mustahil namun terus kucoba.",
    textEn: "Forgetting you is like trying to remember someone I've never met; impossible, yet I keep trying.",
    author: "Original",
    category: "Galau",
  ),
  Quote(
    text: "Jangan menangisi matahari yang tenggelam, karena air matamu akan menghalangimu melihat indahnya bintang.",
    textEn: "Do not weep for the setting sun, for your tears will prevent you from seeing the beauty of the stars.",
    author: "Rabindranath Tagore",
    category: "Galau",
  ),
  Quote(
    text: "Ikhlas itu bukan melepaskan beban, tapi melepaskan harapan pada bahu yang salah.",
    textEn: "Sincerity is not about releasing a burden, but about releasing hope from the wrong shoulders.",
    author: "Original",
    category: "Galau",
  ),
  Quote(
    text: "Kadang kita harus berhenti peduli pada seseorang, bukan karena kita benci, tapi karena dia sudah terlalu bahagia tanpa kita.",
    textEn: "Sometimes we must stop caring about someone, not because we hate them, but because they are already too happy without us.",
    author: "Anonim",
    category: "Galau",
  ),
  Quote(
    text: "Luka yang tak berdarah adalah luka yang paling lambat sembuhnya.",
    textEn: "The wound that does not bleed is the one that is slowest to heal.",
    author: "Agatha Christie",
    category: "Galau",
  ),
  Quote(
    text: "Sabar itu pahit, tapi buahnya lebih manis daripada madu.",
    textEn: "Patience is bitter, but its fruit is sweeter than honey.",
    author: "Imam Al-Ghazali",
    category: "Galau",
  ),
  Quote(
    text: "Kita hanyalah dua orang asing yang kebetulan memiliki kenangan yang sama, lalu kembali menjadi asing.",
    textEn: "We are just two strangers who happened to share the same memories, only to become strangers again.",
    author: "Original",
    category: "Galau",
  ),
  Quote(
    text: "Mencintai sendirian itu seperti menunggu kapal di bandara, kamu menunggu sesuatu yang tak mungkin datang.",
    textEn: "Loving alone is like waiting for a ship at an airport; you are waiting for something that can never arrive.",
    author: "Film AADC 2 (Diadaptasi)",
    category: "Galau",
  ),
  Quote(
    text: "Tenanglah, apa yang melewatkanmu tidak akan pernah menjadi takdirmu, dan apa yang ditakdirkan untukmu tidak akan pernah melewatkanmu.",
    textEn: "Be at peace; what missed you was never your destiny, and what is destined for you will never miss you.",
    author: "Umar bin Khattab",
    category: "Galau",
  ),
  Quote(
    text: "Perpisahan yang paling menyakitkan adalah perpisahan yang tak terucap, namun hati sudah saling menjauh.",
    textEn: "The most painful parting is the one left unsaid, while hearts have already grown apart.",
    author: "Original",
    category: "Galau",
  ),
  Quote(
    text: "Lebih baik patah hati karena kejujuran daripada bahagia di atas kebohongan.",
    textEn: "It is better to be heartbroken by the truth than to be happy based on a lie.",
    author: "Liyana",
    category: "Galau",
  ),
  Quote(
    text: "Ketika hatimu hancur, ingatlah bahwa Allah sedang membangunnya kembali menjadi sesuatu yang lebih kuat.",
    textEn: "When your heart is broken, remember that Allah is rebuilding it into something stronger.",
    author: "Mufti Menk",
    category: "Galau",
  ),
  Quote(
    text: "Aku belajar diam dari banyaknya bicara, belajar sabar dari sebuah kemarahan, dan belajar mengalah dari keegoisan.",
    textEn: "I learned silence from the talkative, patience from the angry, and kindness from the selfish.",
    author: "Kahlil Gibran",
    category: "Galau",
  ),
  Quote(
    text: "Semesta punya cara unik untuk mempertemukan, namun juga punya cara kejam untuk memisahkan.",
    textEn: "The universe has a unique way of bringing us together, but a cruel way of tearing us apart.",
    author: "Original",
    category: "Galau",
  ),
  Quote(
    text: "Ada saatnya kau harus sadar, bahwa berjuang sendirian itu tidak disebut cinta, tapi hukuman.",
    textEn: "There comes a time when you must realize that fighting alone isn't called love, it's called punishment.",
    author: "Raditya Dika (Diadaptasi)",
    category: "Galau",
  ),
  Quote(
    text: "Memaafkan adalah balas dendam terbaik. Lupakan dan biarkan Allah yang mengatur sisanya.",
    textEn: "Forgiveness is the best revenge. Forget it and let Allah handle the rest.",
    author: "Ali bin Abi Thalib",
    category: "Galau",
  ),
  Quote(
    text: "Rindu ini curang, dia bertambah tanpa tahu bagaimana caranya berkurang.",
    textEn: "This longing is unfair; it grows without ever knowing how to fade.",
    author: "Original",
    category: "Galau",
  ),
  Quote(
    text: "Beberapa orang hadir dalam hidupmu hanya untuk menjadi pelajaran, bukan teman hidup.",
    textEn: "Some people come into your life only to be a lesson, not a life partner.",
    author: "Anonim",
    category: "Galau",
  ),
  Quote(
    text: "Langit tidak selamanya cerah, begitu juga hati. Izinkan dirimu bersedih, tapi jangan lupa untuk bangkit kembali.",
    textEn: "The sky isn't always bright, and neither is the heart. Allow yourself to be sad, but don't forget to rise again.",
    author: "Original",
    category: "Galau",
  ),
  Quote(
    text: "Obat terbaik bagi hati yang terluka adalah sujud yang panjang.",
    textEn: "The best medicine for a wounded heart is a long prostration.",
    author: "Ibnu Qayyim",
    category: "Galau",
  ),
  Quote(
    text: "Kita sibuk mencari yang sempurna, hingga kehilangan yang terbaik.",
    textEn: "We are so busy looking for the perfect one that we lose the best one.",
    author: "B.J. Habibie",
    category: "Galau",
  ),
  Quote(
    text: "Hal tersulit dalam hidup bukanlah memilih, tapi bertahan pada pilihan meski terluka.",
    textEn: "The hardest thing in life is not making a choice, but standing by that choice even when it hurts.",
    author: "Original",
    category: "Galau",
  ),
  Quote(
    text: "Air mata adalah doa-doa yang tak mampu diucapkan oleh lisan, namun didengar oleh Tuhan.",
    textEn: "Tears are prayers that cannot be spoken by the tongue but are heard by God.",
    author: "Buya Hamka (Diadaptasi)",
    category: "Galau",
  ),
  Quote(
    text: "Aku tidak memblokirmu, aku hanya menghapusmu dari daftar orang yang kuperjuangkan.",
    textEn: "I didn't block you; I simply removed you from the list of people I fight for.",
    author: "Anonim",
    category: "Galau",
  ),
  Quote(
    text: "Cinta tak pernah salah, hanya waktu dan orangnya yang terkadang belum tepat.",
    textEn: "Love is never wrong; it's just that the time and the person aren't always right yet.",
    author: "Original",
    category: "Galau",
  ),
  Quote(
    text: "Hati yang patah adalah celah bagi cahaya Tuhan untuk masuk.",
    textEn: "The broken heart is the crack through which God's light enters.",
    author: "Jalaluddin Rumi",
    category: "Galau",
  ),
  Quote(
    text: "Berhenti mencari dia yang telah pergi, mulailah memperbaiki diri untuk dia yang akan datang.",
    textEn: "Stop looking for the one who has left; start improving yourself for the one who will arrive.",
    author: "Original",
    category: "Galau",
  ),
  Quote(
    text: "Kenangan adalah satu-satunya surga yang tidak bisa diusir dari kita, sekaligus neraka yang kita ciptakan sendiri.",
    textEn: "Memories are the only paradise from which we cannot be driven, yet they are also the hell we create for ourselves.",
    author: "Jean Paul Richter (Diadaptasi)",
    category: "Galau",
  ),
  Quote(
    text: "Jangan menjelaskan tentang dirimu kepada siapa pun, karena yang menyukaimu tidak butuh itu, dan yang membencimu tidak percaya itu.",
    textEn: "Don't explain yourself to anyone, because those who like you don't need it, and those who hate you won't believe it.",
    author: "Ali bin Abi Thalib",
    category: "Galau",
  ),
  Quote(
    text: "Kadang kita rindu seseorang, tapi sadar bahwa rindu itu tidak punya tempat untuk pulang.",
    textEn: "Sometimes we miss someone, only to realize that the longing has no place to call home.",
    author: "Original",
    category: "Galau",
  ),
  Quote(
    text: "Setiap \"selamat tinggal\" mengajarkan kita cara menghargai sebuah pertemuan.",
    textEn: "Every \"goodbye\" teaches us how to value a meeting.",
    author: "Boy Candra",
    category: "Galau",
  ),
  Quote(
    text: "Jika sabar adalah barang yang diperjualbelikan, maka penantinya adalah orang paling kaya.",
    textEn: "If patience were a commodity to be sold, then those who wait would be the wealthiest.",
    author: "Imam Syafi'i",
    category: "Galau",
  ),
  Quote(
    text: "Cinta sejati tidak berakhir dengan perpisahan, ia hanya berganti wujud menjadi doa.",
    textEn: "True love does not end with parting; it simply transforms into a prayer.",
    author: "Original",
    category: "Galau",
  ),
  Quote(
    text: "Kamu tidak akan pernah menemukan orang yang tepat jika kamu tidak selesai dengan orang yang salah.",
    textEn: "You will never find the right person if you aren't finished with the wrong one.",
    author: "Anonim",
    category: "Galau",
  ),
  Quote(
    text: "Tuhan tidak menjanjikan langit selalu biru, tapi Dia menjanjikan kekuatan di setiap badai.",
    textEn: "God doesn't promise that the sky will always be blue, but He promises strength in every storm.",
    author: "Mutiara Bijak",
    category: "Galau",
  ),
  Quote(
    text: "Puncak tertinggi dari mencintai adalah mengikhlaskan dia bahagia, meski bukan denganmu.",
    textEn: "The highest peak of loving is letting them be happy, even if it's not with you.",
    author: "Original",
    category: "Galau",
  ),
  Quote(
    text: "Kesedihan adalah tamu yang datang tanpa diundang, layani dia sebentar lalu biarkan dia pulang.",
    textEn: "Sadness is an uninvited guest; host it for a while, then let it go home.",
    author: "Original",
    category: "Galau",
  ),
  Quote(
    text: "Jangan risaukan apa yang tidak kau miliki, risaukanlah apa yang kau miliki namun tidak kau syukuri.",
    textEn: "Don't worry about what you don't have; worry about what you have but fail to appreciate.",
    author: "Cak Nun",
    category: "Galau",
  ),
  Quote(
    text: "Pada akhirnya, kita hanyalah memori bagi orang lain. Pastikan memori itu indah.",
    textEn: "In the end, we are just memories for others. Make sure those memories are beautiful.",
    author: "Anonim",
    category: "Galau",
  ),
  Quote(
    text: "Waktu tidak menyembuhkan apa-apa, ia hanya mengajarkan kita bagaimana hidup dengan rasa sakit.",
    textEn: "Time heals nothing; it only teaches us how to live with the pain.",
    author: "Original",
    category: "Galau",
  ),
  Quote(
    text: "Hati manusia itu seperti kaca, jangan terlalu sering digores, nanti retak dan tak bisa berkaca lagi.",
    textEn: "A human heart is like glass; don't scratch it too often, or it will crack and no longer reflect.",
    author: "Imam Ghazali (Diadaptasi)",
    category: "Galau",
  ),
  Quote(
    text: "Cukuplah Allah menjadi penolongmu ketika bahu manusia terlalu lemah untuk kau sandari.",
    textEn: "Let Allah be your helper when human shoulders are too weak for you to lean on.",
    author: "Al-Quran (Inspirasi)",
    category: "Galau",
  ),
  Quote(
    text: "Mencintaimu adalah seni menunggu kabar yang tak kunjung datang, namun hati enggan untuk beranjak.",
    textEn: "Loving you is the art of waiting for news that never comes, yet the heart refuses to move on.",
    author: "Original",
    category: "Galau",
  ),
  Quote(
    text: "Terkadang kita harus menerima bahwa ada orang yang hanya ada di hati kita, tapi tidak dalam hidup kita.",
    textEn: "Sometimes we have to accept that some people remain in our hearts, but not in our lives.",
    author: "Anonim",
    category: "Galau",
  ),
  Quote(
    text: "Sebaik-baiknya perpisahan adalah yang mengajarkan kita untuk kembali mencintai Sang Pencipta lebih dari ciptaan-Nya.",
    textEn: "The best parting is the one that teaches us to love the Creator more than His creation.",
    author: "Islamic Quotes",
    category: "Galau",
  ),
  Quote(
    text: "Jangan jadikan seseorang sebagai prioritas utamamu ketika kamu hanya menjadi pilihan baginya.",
    textEn: "Never make someone a priority when you are only an option to them.",
    author: "Maya Angelou",
    category: "Galau",
  ),
  Quote(
    text: "Rindu yang paling menyiksa adalah merindukan seseorang yang pernah ada di sisimu, namun kini terasa begitu asing.",
    textEn: "The most agonizing longing is missing someone who was once by your side but now feels like a complete stranger.",
    author: "Original",
    category: "Galau",
  ),
  Quote(
    text: "Air mata tidak akan mengembalikan kematian, dan kesedihan tidak akan mengembalikan yang hilang. Serahkan pada Allah.",
    textEn: "Tears won't return the dead, and grief won't return what is lost. Leave it to Allah.",
    author: "Hasan Al-Basri",
    category: "Galau",
  ),
  Quote(
    text: "Kita sering terluka oleh harapan sendiri, lalu menyalahkan keadaan yang tak sesuai keinginan.",
    textEn: "We are often hurt by our own expectations, then blame circumstances for not meeting our desires.",
    author: "Original",
    category: "Galau",
  ),
  Quote(
    text: "Lebih baik menjauh demi menjaga hati, daripada mendekat namun saling menyakiti.",
    textEn: "It is better to distance yourself to protect your heart than to stay close and hurt each other.",
    author: "Tere Liye (Diadaptasi)",
    category: "Galau",
  ),
  Quote(
    text: "Hati ini ibarat rumah, jika penghuninya memutuskan pergi, jangan biarkan pintunya terbuka selamanya untuk debu dan angin.",
    textEn: "The heart is like a house; if its dweller decides to leave, don't leave the door open forever for dust and wind.",
    author: "Original",
    category: "Galau",
  ),
  Quote(
    text: "Ketahuilah, apa yang menimpa tidak akan luput darimu, dan apa yang luput darimu tidak akan menimpamu. Itu takdir.",
    textEn: "Know that what strikes you was not meant to miss you, and what misses you was not meant to strike you. That is destiny.",
    author: "HR. Abu Daud",
    category: "Galau",
  ),
  Quote(
    text: "Cemburu tanpa status adalah patah hati paling rahasia yang pernah ada.",
    textEn: "Jealousy without a status is the most secret heartbreak that ever existed.",
    author: "Raditya Dika",
    category: "Galau",
  ),
  Quote(
    text: "Senja mengajarkan kita bahwa sesuatu yang indah pun ada akhirnya, namun akan terbit keindahan baru esok hari.",
    textEn: "Sunset teaches us that even beautiful things come to an end, yet a new beauty will rise tomorrow.",
    author: "Original",
    category: "Galau",
  ),
  Quote(
    text: "Berpura-pura bahagia itu melelahkan, tapi menjelaskan kesedihan kepada orang yang tak peduli jauh lebih menyakitkan.",
    textEn: "Pretending to be happy is exhausting, but explaining sadness to those who don't care is much more painful.",
    author: "Joker (Diadaptasi)",
    category: "Galau",
  ),
  Quote(
    text: "Jika namamu yang tertulis di Lauhul Mahfudz untukku, niscaya Allah akan menanamkan rasa cinta di hatimu untukku.",
    textEn: "If your name is written in the Preserved Tablet for me, surely Allah will plant love in your heart for me.",
    author: "Cinta dalam Diam",
    category: "Galau",
  ),
  Quote(
    text: "Aku mundur bukan karena tidak sayang, tapi karena sadar posisiku tak pernah kau anggap penting.",
    textEn: "I am stepping back not because I don't care, but because I realize my position was never important to you.",
    author: "Original",
    category: "Galau",
  ),
  Quote(
    text: "Luka lama belum sembuh, jangan mengundang orang baru hanya untuk menjadi pelampiasan.",
    textEn: "Old wounds haven't healed; don't invite someone new just to be a rebound.",
    author: "Fiersa Besari (Inspirasi)",
    category: "Galau",
  ),
  Quote(
    text: "Ada yang pamit tanpa permisi, ada yang pergi tanpa kata, meninggalkan tanya yang tak terjawab selamanya.",
    textEn: "Some leave without permission, some go without a word, leaving questions that will never be answered.",
    author: "Original",
    category: "Galau",
  ),
  Quote(
    text: "Dunia ini ibarat bayangan. Kejar dia, dia lari. Berpalinglah darinya, dia tak punya pilihan selain mengikutimu.",
    textEn: "This world is like a shadow. Chase it, and it runs. Turn away from it, and it has no choice but to follow you.",
    author: "Ibnu Qayyim",
    category: "Galau",
  ),
  Quote(
    text: "Menangis bukan tanda lemah, itu tanda bahwa hatimu masih hidup dan perasamu masih berfungsi.",
    textEn: "Crying is not a sign of weakness; it's a sign that your heart is still alive and your feelings still function.",
    author: "Anonim",
    category: "Galau",
  ),
  Quote(
    text: "Seringkali kita merindukan kenangannya, bukan orangnya.",
    textEn: "Often we miss the memory, not the person.",
    author: "Original",
    category: "Galau",
  ),
  Quote(
    text: "Jangan menjelaskan betapa besar cintamu, tapi buktikan dengan seberapa kuat sabarmu.",
    textEn: "Don't explain how great your love is, but prove it with how strong your patience is.",
    author: "Mario Teguh (Diadaptasi)",
    category: "Galau",
  ),
  Quote(
    text: "Kecewa adalah cara Tuhan mengatakan: 'Bangun, Aku punya sesuatu yang lebih baik dari yang sedang kau tangisi'.",
    textEn: "Disappointment is God's way of saying: 'Wake up, I have something better than what you are weeping for'.",
    author: "Original",
    category: "Galau",
  ),
  Quote(
    text: "Cinta yang tidak halal itu melelahkan, penuh rasa was-was dan takut kehilangan. Cinta dalam doa itu menenangkan.",
    textEn: "Unlawful love is exhausting, full of anxiety and fear of loss. Love in prayer is peaceful.",
    author: "Nasehat Pernikahan",
    category: "Galau",
  ),
  Quote(
    text: "Jarak hanyalah angka bagi dua orang yang saling mendoakan, namun menjadi jurang bagi mereka yang tak lagi sejalan.",
    textEn: "Distance is just a number for two who pray for each other, but it's an abyss for those no longer on the same path.",
    author: "Original",
    category: "Galau",
  ),
  Quote(
    text: "Pada akhirnya, yang benar-benar milikmu akan kembali, dan yang bukan akan perlahan pergi.",
    textEn: "In the end, what truly belongs to you will return, and what does not will slowly fade away.",
    author: "Heidi Priebe",
    category: "Galau",
  ),
  Quote(
    text: "Sulit untuk memulai bab baru dalam hidup jika kau terus membaca ulang bab terakhir.",
    textEn: "It's hard to start a new chapter in life if you keep re-reading the last one.",
    author: "Anonim",
    category: "Galau",
  ),
  Quote(
    text: "Allah tidak membebani seseorang melainkan sesuai dengan kesanggupannya. Termasuk sanggup menahan rindu.",
    textEn: "Allah does not burden a soul beyond that it can bear. Including the strength to endure longing.",
    author: "Al-Quran (QS Al-Baqarah: 286)",
    category: "Galau",
  ),
  Quote(
    text: "Hujan di luar jendela tak sederas rindu yang membanjiri hati ini.",
    textEn: "The rain outside the window is not as heavy as the longing flooding this heart.",
    author: "Original",
    category: "Galau",
  ),
  Quote(
    text: "Terkadang 'selamat tinggal' hanyalah cara lain untuk mengatakan 'aku mencintaimu, tapi aku harus menyelamatkan diriku'.",
    textEn: "Sometimes 'goodbye' is just another way of saying 'I love you, but I must save myself'.",
    author: "Original",
    category: "Galau",
  ),
  Quote(
    text: "Balas dendam terbaik adalah menjadi sukses, bahagia, and melupakan bahwa mereka pernah menyakiti kita.",
    textEn: "The best revenge is to be successful, happy, and to forget they ever hurt us.",
    author: "Frank Sinatra (Diadaptasi)",
    category: "Galau",
  ),
  Quote(
    text: "Memendam perasaan itu seperti menggenggam bara api; semakin erat kau genggam, semakin sakit luka yang kau buat.",
    textEn: "Suppressing feelings is like holding a hot coal; the tighter you hold it, the more painful the wound you create.",
    author: "Ali bin Abi Thalib (Analogi)",
    category: "Galau",
  ),
  Quote(
    text: "Kita seperti dua rel kereta api, selalu berdampingan namun tak pernah benar-benar menyatu.",
    textEn: "We are like two railroad tracks; always side by side but never truly one.",
    author: "Original",
    category: "Galau",
  ),
  Quote(
    text: "Jangan biarkan hatimu dijajah oleh rasa sedih akan masa lalu atau kecemasan akan masa depan. Hiduplah hari ini.",
    textEn: "Don't let your heart be occupied by sorrow for the past or anxiety for the future. Live for today.",
    author: "Aidh Al-Qarni",
    category: "Galau",
  ),
  Quote(
    text: "Aku belajar bahwa memaksakan sesuatu yang bukan takdirku hanya akan menunda pertemuan dengan apa yang sebenarnya milikku.",
    textEn: "I learned that forcing something that isn't my destiny only delays the meeting with what truly belongs to me.",
    author: "Original",
    category: "Galau",
  ),
  Quote(
    text: "Patah hati adalah guru yang keras, tapi dia mengajarkan pelajaran yang tak terlupakan tentang harga diri.",
    textEn: "Heartbreak is a harsh teacher, but it teaches an unforgettable lesson about self-worth.",
    author: "Anonim",
    category: "Galau",
  ),
  Quote(
    text: "Cinta tak butuh alasan, tapi perpisahan selalu punya banyak alasan.",
    textEn: "Love needs no reason, but parting always has many reasons.",
    author: "Pidi Baiq (Dilan)",
    category: "Galau",
  ),
  Quote(
    text: "Obat dari rasa sepi bukanlah keramaian, melainkan kedekatan hati dengan Sang Pemilik Hati.",
    textEn: "The cure for loneliness is not a crowd, but the heart's closeness to the Owner of the Heart.",
    author: "Aa Gym",
    category: "Galau",
  ),
  Quote(
    text: "Mungkin kita dipertemukan hanya untuk saling memberi pelajaran, bukan untuk saling memiliki selamanya.",
    textEn: "Perhaps we were met only to give each other a lesson, not to possess each other forever.",
    author: "Original",
    category: "Galau",
  ),
  Quote(
    text: "Jangan takut melepaskan merpati terbaik, karena jika dia setia, dia akan tahu jalan pulang.",
    textEn: "Do not fear releasing the best dove, for if it is loyal, it will know its way back home.",
    author: "Pepatah Lama",
    category: "Galau",
  ),
  Quote(
    text: "Menunggu itu membosankan, tapi menunggu tanpa kepastian itu mematikan.",
    textEn: "Waiting is boring, but waiting without certainty is fatal.",
    author: "Original",
    category: "Galau",
  ),
  Quote(
    text: "Kunci ketenangan hidup adalah tidak menggantungkan kebahagiaan pada manusia lain.",
    textEn: "The key to a peaceful life is not hanging your happiness on another human being.",
    author: "Habib Umar bin Hafidz",
    category: "Galau",
  ),
  Quote(
    text: "Aku iri pada hujan, ia jatuh tapi tak pernah merasa sakit, ia membasahi bumi lalu hilang diserap tanah.",
    textEn: "I am jealous of the rain; it falls yet never feels pain, it wets the earth then disappears into the ground.",
    author: "Original",
    category: "Galau",
  ),
  Quote(
    text: "Tidak ada yang lebih tabah dari hujan bulan Juni, dirahasiakannya rindu rintiknya kepada pohon berbunga itu.",
    textEn: "Nothing is more patient than the rain in June; it keeps secret its longing drops for the flowering tree.",
    author: "Sapardi Djoko Damono",
    category: "Galau",
  ),
  Quote(
    text: "Kadang kau harus menghilang sejenak untuk melihat siapa yang akan mencarimu.",
    textEn: "Sometimes you must disappear for a while to see who will come looking for you.",
    author: "Anonim",
    category: "Galau",
  ),
  Quote(
    text: "Allah tahu hatimu lelah, tapi Allah juga tahu kapan waktu yang tepat untuk menyembuhkannya.",
    textEn: "Allah knows your heart is tired, but Allah also knows the right time to heal it.",
    author: "Nasehat Muslim",
    category: "Galau",
  ),
  Quote(
    text: "Setiap luka punya cerita, dan setiap cerita membentuk siapa kita hari ini.",
    textEn: "Every wound has a story, and every story shapes who we are today.",
    author: "Original",
    category: "Galau",
  ),
  Quote(
    text: "Jika mencintaimu adalah sebuah kesalahan, maka biarlah aku belajar dari kesalahan itu seumur hidupku.",
    textEn: "If loving you is a mistake, then let me learn from that mistake for the rest of my life.",
    author: "Original",
    category: "Galau",
  ),
  Quote(
    text: "Lebih baik sendiri dalam taat, daripada berdua dalam maksiat yang berujung sakit hati dunia akhirat.",
    textEn: "Better alone in obedience than together in sin that leads to heartbreak in this world and the hereafter.",
    author: "Dakwah Jomblo",
    category: "Galau",
  ),
];