import '../models_daily_free/quote_model.dart';

List<Quote> suksesQuotes = [
  Quote(
    text: "Sukses bukanlah kunci kebahagiaan. Kebahagiaanlah kunci kesuksesan. Jika kamu mencintai apa yang kamu kerjakan, kamu akan sukses.",
    textEn: "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
    author: "Albert Schweitzer",
    category: "Sukses",
  ),
  Quote(
    text: "Jangan takut gagal. Takutlah berada di tempat yang sama tahun depan seperti dirimu hari ini.",
    textEn: "Don't fear failure. Fear being in the same place next year as you are today.",
    author: "Anonim",
    category: "Sukses",
  ),
  Quote(
    text: "Peluang tidak terjadi begitu saja, kamulah yang menciptakannya melalui kerja keras dan persiapan.",
    textEn: "Opportunities don't happen, you create them through hard work and preparation.",
    author: "Chris Grosser",
    category: "Sukses",
  ),
  Quote(
    text: "Satu-satunya cara untuk melakukan pekerjaan hebat adalah dengan mencintai apa yang kamu lakukan.",
    textEn: "The only way to do great work is to love what you do.",
    author: "Steve Jobs",
    category: "Sukses",
  ),
  Quote(
    text: "Jangan menunggu waktu yang tepat. Ciptakan waktu itu sekarang dan mulailah melangkah.",
    textEn: "Don't wait for the right time. Create it now and start moving.",
    author: "Napoleon Hill",
    category: "Sukses",
  ),
  Quote(
    text: "Sukses adalah berjalan dari satu kegagalan ke kegagalan lain tanpa kehilangan antusiasme.",
    textEn: "Success is stumbling from failure to failure with no loss of enthusiasm.",
    author: "Winston Churchill",
    category: "Sukses",
  ),
  Quote(
    text: "Masa depan adalah milik mereka yang percaya pada keindahan mimpi-mimpi mereka.",
    textEn: "The future belongs to those who believe in the beauty of their dreams.",
    author: "Eleanor Roosevelt",
    category: "Sukses",
  ),
  Quote(
    text: "Jangan berharap pekerjaanmu menjadi lebih mudah, berharaplah dirimu menjadi lebih baik.",
    textEn: "Don't wish it were easier, wish you were better.",
    author: "Jim Rohn",
    category: "Sukses",
  ),
  Quote(
    text: "Disiplin adalah jembatan antara tujuan dan pencapaian.",
    textEn: "Discipline is the bridge between goals and accomplishment.",
    author: "Jim Rohn",
    category: "Sukses",
  ),
  Quote(
    text: "Orang yang memindahkan gunung memulainya dengan memindahkan batu-batu kecil.",
    textEn: "The man who moves a mountain begins by carrying away small stones.",
    author: "Confucius",
    category: "Sukses",
  ),
  Quote(
    text: "Rahasia kesuksesan adalah mengetahui sesuatu yang tidak diketahui orang lain.",
    textEn: "The secret to success is to know something nobody else knows.",
    author: "Aristotle Onassis",
    category: "Sukses",
  ),
  Quote(
    text: "Bekerja keraslah dalam diam, biarkan kesuksesanmu yang membuat keributan.",
    textEn: "Work hard in silence, let your success be your noise.",
    author: "Frank Ocean",
    category: "Sukses",
  ),
  Quote(
    text: "Jangan melihat jam; lakukan apa yang ia lakukan. Teruslah bergerak maju.",
    textEn: "Don't watch the clock; do what it does. Keep going.",
    author: "Sam Levenson",
    category: "Sukses",
  ),
  Quote(
    text: "Resiko terbesar adalah tidak mengambil resiko sama sekali.",
    textEn: "The biggest risk is not taking any risk.",
    author: "Mark Zuckerberg",
    category: "Sukses",
  ),
  Quote(
    text: "Sukses bukanlah kebetulan. Ia adalah kerja keras, ketekunan, belajar, berkorban, dan yang terpenting, mencintai apa yang kamu lakukan.",
    textEn: "Success is no accident. It is hard work, perseverance, learning, sacrifice and most of all, love of what you are doing.",
    author: "Pele",
    category: "Sukses",
  ),
  Quote(
    text: "Jatuh tujuh kali, bangkit delapan kali.",
    textEn: "Fall seven times, stand up eight.",
    author: "Peribahasa Jepang",
    category: "Sukses",
  ),
  Quote(
    text: "Jika kamu tidak membangun mimpimu sendiri, seseorang akan mempekerjakanmu untuk membangun mimpi mereka.",
    textEn: "If you don't build your dream, someone will hire you to build theirs.",
    author: "Tony Gaskins",
    category: "Sukses",
  ),
  Quote(
    text: "Seseorang yang berani membuang satu jam waktunya, belum mengetahui nilai dari kehidupan.",
    textEn: "A man who dares to waste one hour of time has not discovered the value of life.",
    author: "Charles Darwin",
    category: "Sukses",
  ),
  Quote(
    text: "Hambatan adalah hal-hal menakutkan yang kamu lihat ketika kamu mengalihkan pandangan dari tujuanmu.",
    textEn: "Obstacles are those frightful things you see when you take your eyes off your goal.",
    author: "Henry Ford",
    category: "Sukses",
  ),
  Quote(
    text: "Tidak ada lift menuju kesuksesan. Kamu harus menaiki tangga.",
    textEn: "There is no elevator to success. You have to take the stairs.",
    author: "Zig Ziglar",
    category: "Sukses",
  ),
  Quote(
    text: "Investasi dalam pengetahuan selalu membayar bunga terbaik.",
    textEn: "An investment in knowledge pays the best interest.",
    author: "Benjamin Franklin",
    category: "Sukses",
  ),
  Quote(
    text: "Man jadda wajada. Barang siapa yang bersungguh-sungguh, maka ia akan berhasil.",
    textEn: "Man jadda wajada. He who strives with sincerity shall succeed.",
    author: "Pepatah Arab",
    category: "Sukses",
  ),
  Quote(
    text: "Balas dendam terbaik adalah kesuksesan besar.",
    textEn: "The best revenge is massive success.",
    author: "Frank Sinatra",
    category: "Sukses",
  ),
  Quote(
    text: "Mulailah dari mana kamu berada. Gunakan apa yang kamu miliki. Lakukan apa yang kamu bisa.",
    textEn: "Start where you are. Use what you have. Do what you can.",
    author: "Arthur Ashe",
    category: "Sukses",
  ),
  Quote(
    text: "Kesabaran itu pahit, tapi buahnya manis.",
    textEn: "Patience is bitter, but its fruit is sweet.",
    author: "Aristoteles",
    category: "Sukses",
  ),
  Quote(
    text: "Orang pesimis melihat kesulitan di setiap kesempatan. Orang optimis melihat kesempatan di setiap kesulitan.",
    textEn: "A pessimist sees the difficulty in every opportunity; an optimist sees the opportunity in every difficulty.",
    author: "Winston Churchill",
    category: "Sukses",
  ),
  Quote(
    text: "Tindakan adalah kunci dasar untuk semua kesuksesan.",
    textEn: "Action is the foundational key to all success.",
    author: "Pablo Picasso",
    category: "Sukses",
  ),
  Quote(
    text: "Kualitas hidupmu berbanding lurus dengan komitmenmu terhadap keunggulan, apapun bidang yang kamu pilih.",
    textEn: "The quality of your life is in direct proportion to your commitment to excellence, regardless of your chosen field.",
    author: "Vince Lombardi",
    category: "Sukses",
  ),
  Quote(
    text: "Sukses tidak diukur dari apa yang telah kamu capai, tetapi dari rintangan yang telah kamu atasi.",
    textEn: "Success is to be measured not so much by the position that one has reached, but by the obstacles which he has overcome.",
    author: "Booker T. Washington",
    category: "Sukses",
  ),
  Quote(
    text: "Waktumu terbatas, jadi jangan sia-siakan dengan menjalani hidup orang lain.",
    textEn: "Your time is limited, so don't waste it living someone else's life.",
    author: "Steve Jobs",
    category: "Sukses",
  ),
  Quote(
    text: "Visi tanpa eksekusi hanyalah halusinasi.",
    textEn: "Vision without execution is hallucination.",
    author: "Thomas Edison",
    category: "Sukses",
  ),
  Quote(
    text: "Jangan biarkan hari kemarin menyita terlalu banyak dari hari ini.",
    textEn: "Don't let yesterday take up too much of today.",
    author: "Will Rogers",
    category: "Sukses",
  ),
  Quote(
    text: "Kreativitas adalah kecerdasan yang bersenang-senang.",
    textEn: "Creativity is intelligence having fun.",
    author: "Albert Einstein",
    category: "Sukses",
  ),
  Quote(
    text: "Bakat memenangkan pertandingan, tetapi kerja tim dan kecerdasan memenangkan kejuaraan.",
    textEn: "Talent wins games, but teamwork and intelligence win championships.",
    author: "Michael Jordan",
    category: "Sukses",
  ),
  Quote(
    text: "Jadilah perubahan yang ingin kamu lihat di dunia.",
    textEn: "Be the change that you wish to see in the world.",
    author: "Mahatma Gandhi",
    category: "Sukses",
  ),
  Quote(
    text: "Pekerjaan hebat biasanya dilakukan oleh orang-orang yang tidak takut menjadi hebat.",
    textEn: "Great work is usually done by people who are not afraid to be great.",
    author: "Fernando Flores",
    category: "Sukses",
  ),
  Quote(
    text: "Logika akan membawamu dari A ke B. Imajinasi akan membawamu ke mana saja.",
    textEn: "Logic will get you from A to B. Imagination will take you everywhere.",
    author: "Albert Einstein",
    category: "Sukses",
  ),
  Quote(
    text: "Keberanian adalah ketahanan terhadap rasa takut, penguasaan rasa takut, bukan ketiadaan rasa takut.",
    textEn: "Courage is resistance to fear, mastery of fear, not absence of fear.",
    author: "Mark Twain",
    category: "Sukses",
  ),
  Quote(
    text: "Sebaik-baik manusia adalah yang paling bermanfaat bagi orang lain.",
    textEn: "The best of people are those who are most beneficial to others.",
    author: "HR. Ahmad",
    category: "Sukses",
  ),
  Quote(
    text: "Jika rencananya tidak berhasil, ganti rencananya, jangan ganti tujuannya.",
    textEn: "If the plan doesn't work, change the plan, but never the goal.",
    author: "Anonim",
    category: "Sukses",
  ),
  Quote(
    text: "Sukses biasanya datang kepada mereka yang terlalu sibuk untuk mencarinya.",
    textEn: "Success usually comes to those who are too busy to be looking for it.",
    author: "Henry David Thoreau",
    category: "Sukses",
  ),
  Quote(
    text: "Satu ons tindakan bernilai satu ton teori.",
    textEn: "An ounce of action is worth a ton of theory.",
    author: "Ralph Waldo Emerson",
    category: "Sukses",
  ),
  Quote(
    text: "Jangan malu dengan kegagalanmu, belajarlah darinya dan mulai lagi.",
    textEn: "Do not be embarrassed by your failures, learn from them and start again.",
    author: "Richard Branson",
    category: "Sukses",
  ),
  Quote(
    text: "Keyakinan tanpa ilmu itu buta, ilmu tanpa keyakinan itu lumpuh.",
    textEn: "Faith without knowledge is blind, knowledge without faith is lame.",
    author: "Albert Einstein",
    category: "Sukses",
  ),
  Quote(
    text: "Rezeki sudah diatur, tapi ia tidak akan datang kepada orang yang hanya duduk diam.",
    textEn: "Provision is already set, but it will not come to those who only sit still.",
    author: "Anonim",
    category: "Sukses",
  ),
  Quote(
    text: "Perjalanan seribu mil dimulai dengan satu langkah.",
    textEn: "A journey of a thousand miles begins with a single step.",
    author: "Lao Tzu",
    category: "Sukses",
  ),
  Quote(
    text: "Fokuslah menjadi produktif, bukan sekadar sibuk.",
    textEn: "Focus on being productive instead of busy.",
    author: "Tim Ferriss",
    category: "Sukses",
  ),
  Quote(
    text: "Mimpi tidak akan menjadi kenyataan melalui sihir; itu membutuhkan keringat, tekad, dan kerja keras.",
    textEn: "A dream doesn't become reality through magic; it takes sweat, determination and hard work.",
    author: "Colin Powell",
    category: "Sukses",
  ),
  Quote(
    text: "Bukan yang terkuat yang bertahan, bukan juga yang paling pintar, tetapi yang paling responsif terhadap perubahan.",
    textEn: "It is not the strongest of the species that survives, nor the most intelligent; it is the one most adaptable to change.",
    author: "Charles Darwin",
    category: "Sukses",
  ),
  Quote(
    text: "Sukses adalah jumlah dari usaha kecil yang diulang hari demi hari.",
    textEn: "Success is the sum of small efforts, repeated day in and day out.",
    author: "Robert Collier",
    category: "Sukses",
  ),
  Quote(
    text: "Jangan pernah menyerah pada apa yang benar-benar ingin kamu lakukan. Orang dengan mimpi besar lebih kuat daripada orang dengan semua fakta.",
    textEn: "Never give up on what you really want to do. The person with big dreams is more powerful than one with all the facts.",
    author: "H. Jackson Brown Jr.",
    category: "Sukses",
  ),
  Quote(
    text: "Nilai dari seseorang itu ditentukan dari keberaniannya memikul tanggung jawab, mencintai, dan menikmati hidup.",
    textEn: "The value of a person is determined by their courage to take responsibility, to love, and to enjoy life.",
    author: "William Shakespeare",
    category: "Sukses",
  ),
  Quote(
    text: "Jika sesuatu itu cukup penting, kamu harus tetap melakukannya meskipun peluang tidak berpihak padamu.",
    textEn: "If something is important enough, even if the odds are against you, you should still do it.",
    author: "Elon Musk",
    category: "Sukses",
  ),
  Quote(
    text: "Hari ini sulit, besok akan lebih buruk, tetapi lusa akan menjadi hari yang indah.",
    textEn: "Today is hard, tomorrow is worse, but the day after tomorrow will be sunshine.",
    author: "Jack Ma",
    category: "Sukses",
  ),
  Quote(
    text: "Dibutuhkan 20 tahun untuk membangun reputasi dan lima menit untuk menghancurkannya.",
    textEn: "It takes 20 years to build a reputation and five minutes to ruin it.",
    author: "Warren Buffett",
    category: "Sukses",
  ),
  Quote(
    text: "Pelangganmu yang paling tidak bahagia adalah sumber belajar terbesarmu.",
    textEn: "Your most unhappy customers are your greatest source of learning.",
    author: "Bill Gates",
    category: "Sukses",
  ),
  Quote(
    text: "Ubah lukamu menjadi kebijaksanaan.",
    textEn: "Turn your wounds into wisdom.",
    author: "Oprah Winfrey",
    category: "Sukses",
  ),
  Quote(
    text: "Jika kamu tidak sanggup menahan lelahnya belajar, maka kamu harus sanggup menahan perihnya kebodohan.",
    textEn: "If you cannot endure the fatigue of study, you must endure the pain of ignorance.",
    author: "Imam Syafi'i",
    category: "Sukses",
  ),
  Quote(
    text: "Saya tidak pernah bermimpi tentang kesuksesan. Saya bekerja untuk itu.",
    textEn: "I never dreamed about success. I worked for it.",
    author: "Est�e Lauder",
    category: "Sukses",
  ),
  Quote(
    text: "Cara terbaik memprediksi masa depan adalah dengan menciptakannya.",
    textEn: "The best way to predict the future is to create it.",
    author: "Peter Drucker",
    category: "Sukses",
  ),
  Quote(
    text: "Ketakutan membunuh lebih banyak mimpi daripada kegagalan.",
    textEn: "Fear kills more dreams than failure ever will.",
    author: "Suzy Kassem",
    category: "Sukses",
  ),
  Quote(
    text: "Jangan bekerja untuk uang, biarkan uang bekerja untukmu.",
    textEn: "Don't work for money; make money work for you.",
    author: "Robert Kiyosaki",
    category: "Sukses",
  ),
  Quote(
    text: "Sukses adalah menyukai diri sendiri, menyukai apa yang kamu lakukan, dan menyukai bagaimana kamu melakukannya.",
    textEn: "Success is liking yourself, liking what you do, and liking how you do it.",
    author: "Maya Angelou",
    category: "Sukses",
  ),
  Quote(
    text: "Bekerjalah sampai idolamu menjadi sainganmu.",
    textEn: "Work until your idols become your rivals.",
    author: "Drake",
    category: "Sukses",
  ),
  Quote(
    text: "Jangan menurunkan impianmu agar sesuai dengan kenyataan, tingkatkan keyakinanmu agar sesuai dengan takdirmu.",
    textEn: "Don't drop your dreams to fit reality; upgrade your faith to match your destiny.",
    author: "Stuart Scott",
    category: "Sukses",
  ),
  Quote(
    text: "Bukan spesies yang paling kuat yang bertahan, tapi yang paling bisa beradaptasi.",
    textEn: "It is not the strongest of the species that survives, but the one most adaptable.",
    author: "Leon C. Megginson",
    category: "Sukses",
  ),
  Quote(
    text: "Keberuntungan adalah dividen dari keringat. Semakin banyak kamu berkeringat, semakin beruntung kamu.",
    textEn: "Luck is a dividend of sweat. The more you sweat, the luckier you get.",
    author: "Ray Kroc",
    category: "Sukses",
  ),
  Quote(
    text: "Tangan di atas (memberi) lebih baik daripada tangan di bawah (meminta).",
    textEn: "The upper hand (giving) is better than the lower hand (asking).",
    author: "HR. Bukhari",
    category: "Sukses",
  ),
  Quote(
    text: "Orang sukses punya perpustakaan besar. Orang biasa punya TV besar.",
    textEn: "Successful people have big libraries. Ordinary people have big TVs.",
    author: "Jim Rohn",
    category: "Sukses",
  ),
  Quote(
    text: "Prajurit yang menang menang dulu baru pergi berperang, prajurit yang kalah pergi berperang dulu baru berusaha menang.",
    textEn: "Victorious warriors win first and then go to war, while defeated warriors go to war first and then seek to win.",
    author: "Sun Tzu",
    category: "Sukses",
  ),
  Quote(
    text: "Risikolah lebih dari yang orang lain anggap aman. Bermimpilah lebih dari yang orang lain anggap masuk akal.",
    textEn: "Risk more than others think is safe. Dream more than others think is practical.",
    author: "Howard Schultz",
    category: "Sukses",
  ),
  Quote(
    text: "Saya tidak takut pada orang yang berlatih 10.000 tendangan sekali, tapi saya takut pada orang yang berlatih satu tendangan 10.000 kali.",
    textEn: "I fear not the man who has practiced 10,000 kicks once, but I fear the man who has practiced one kick 10,000 times.",
    author: "Bruce Lee",
    category: "Sukses",
  ),
  Quote(
    text: "Kepemimpinan adalah kemampuan menerjemahkan visi menjadi kenyataan.",
    textEn: "Leadership is the capacity to translate vision into reality.",
    author: "Warren Bennis",
    category: "Sukses",
  ),
  Quote(
    text: "Jika kamu ingin terbang, kamu harus melepaskan hal-hal yang membebanimu.",
    textEn: "If you want to fly, you have to give up the things that weigh you down.",
    author: "Toni Morrison",
    category: "Sukses",
  ),
  Quote(
    text: "Keraguan membunuh lebih banyak mimpi daripada kegagalan.",
    textEn: "Doubt kills more dreams than failure ever will.",
    author: "Karim Seddiki",
    category: "Sukses",
  ),
  Quote(
    text: "Jangan bernegosiasi dengan kemalasanmu.",
    textEn: "Don't negotiate with your laziness.",
    author: "Anonim",
    category: "Sukses",
  ),
  Quote(
    text: "Genius adalah 1% inspirasi dan 99% keringat.",
    textEn: "Genius is one percent inspiration and ninety-nine percent perspiration.",
    author: "Thomas Edison",
    category: "Sukses",
  ),
  Quote(
    text: "Berhenti mengejar uang dan mulailah mengejar hasrat (passion).",
    textEn: "Stop chasing the money and start chasing the passion.",
    author: "Tony Hsieh",
    category: "Sukses",
  ),
  Quote(
    text: "Kesuksesan sering kali dicapai oleh mereka yang tidak tahu bahwa kegagalan itu tidak terelakkan.",
    textEn: "Success is often achieved by those who don't know that failure is inevitable.",
    author: "Coco Chanel",
    category: "Sukses",
  ),
  Quote(
    text: "Tanpa ambisi seseorang tidak memulai apa-apa. Tanpa kerja seseorang tidak menyelesaikan apa-apa.",
    textEn: "Without ambition one starts nothing. Without work one finishes nothing.",
    author: "Ralph Waldo Emerson",
    category: "Sukses",
  ),
  Quote(
    text: "Jaringanmu adalah kekayaan bersihmu (Your network is your net worth).",
    textEn: "Your network is your net worth.",
    author: "Porter Gale",
    category: "Sukses",
  ),
  Quote(
    text: "Jika kamu lahir miskin, itu bukan salahmu. Tapi jika kamu mati miskin, itu salahmu.",
    textEn: "If you are born poor its not your mistake, but if you die poor its your mistake.",
    author: "Bill Gates",
    category: "Sukses",
  ),
  Quote(
    text: "Kecerdasan tanpa ambisi bagaikan burung tanpa sayap.",
    textEn: "Intelligence without ambition is a bird without wings.",
    author: "Salvador Dali",
    category: "Sukses",
  ),
  Quote(
    text: "Harga dari sebuah kehebatan adalah tanggung jawab.",
    textEn: "The price of greatness is responsibility.",
    author: "Winston Churchill",
    category: "Sukses",
  ),
  Quote(
    text: "Lakukan pekerjaan yang sulit dulu. Pekerjaan mudah akan mengurus dirinya sendiri.",
    textEn: "Do the hard jobs first. The easy jobs will take care of themselves.",
    author: "Dale Carnegie",
    category: "Sukses",
  ),
  Quote(
    text: "Inovasi membedakan antara pemimpin dan pengikut.",
    textEn: "Innovation distinguishes between a leader and a follower.",
    author: "Steve Jobs",
    category: "Sukses",
  ),
  Quote(
    text: "Konsistensi adalah kunci. Bahkan tetesan air bisa melubangi batu, bukan karena kekuatan tapi karena ketekunan.",
    textEn: "Consistency is key. Even a drop of water can hollow out a stone, not by force but by persistence.",
    author: "Ovid",
    category: "Sukses",
  ),
  Quote(
    text: "Jangan katakan pada orang tentang rencanamu. Tunjukkan pada mereka hasilmu.",
    textEn: "Don't tell people your plans. Show them your results.",
    author: "Anonim",
    category: "Sukses",
  ),
  Quote(
    text: "Orang yang luar biasa itu sederhana dalam ucapan, tetapi hebat dalam tindakan.",
    textEn: "The superior man is modest in his speech, but exceeds in his actions.",
    author: "Confucius",
    category: "Sukses",
  ),
  Quote(
    text: "Setiap penjualan memiliki lima hambatan dasar: tidak butuh, tidak ada uang, tidak buru-buru, tidak ada keinginan, tidak ada kepercayaan.",
    textEn: "Every sale has five basic obstacles: no need, no money, no hurry, no desire, no trust.",
    author: "Zig Ziglar",
    category: "Sukses",
  ),
  Quote(
    text: "Sukses di bisnis membutuhkan latihan, disiplin, dan kerja keras.",
    textEn: "Success in business requires training and discipline and hard work.",
    author: "David Rockefeller",
    category: "Sukses",
  ),
  Quote(
    text: "Gagal merencanakan berarti merencanakan untuk gagal.",
    textEn: "By failing to prepare, you are preparing to fail.",
    author: "Benjamin Franklin",
    category: "Sukses",
  ),
  Quote(
    text: "Sebaik-baik manusia adalah yang paling bermanfaat bagi sesamanya.",
    textEn: "The best of people are those who are most beneficial to others.",
    author: "HR. Ahmad",
    category: "Sukses",
  ),
  Quote(
    text: "Jangan biarkan suara opini orang lain menenggelamkan suara batinmu sendiri.",
    textEn: "Don't let the noise of others' opinions drown out your own inner voice.",
    author: "Steve Jobs",
    category: "Sukses",
  ),
  Quote(
    text: "Hidup itu 10% apa yang terjadi padamu dan 90% bagaimana kamu bereaksi terhadapnya.",
    textEn: "Life is 10% what happens to you and 90% how you react to it.",
    author: "Charles R. Swindoll",
    category: "Sukses",
  ),
  Quote(
    text: "Kemenangan yang paling manis adalah kemenangan atas diri sendiri.",
    textEn: "The first and greatest victory is to conquer yourself.",
    author: "Plato",
    category: "Sukses",
  ),
  Quote(
    text: "Berani bermimpi, berani mencoba, berani gagal, berani sukses.",
    textEn: "Dare to dream, dare to try, dare to fail, dare to succeed.",
    author: "Anonim",
    category: "Sukses",
  ),
  Quote(
    text: "Kerja cerdas seringkali lebih penting daripada sekadar kerja keras.",
    textEn: "Working smart is often more important than just working hard.",
    author: "Anonim",
    category: "Sukses",
  ),
  Quote(
    text: "Jangan membandingkan progresmu dengan orang lain. Bandingkan dirimu hari ini dengan dirimu yang kemarin.",
    textEn: "Don't compare your progress with others. Compare yourself today with who you were yesterday.",
    author: "Anonim",
    category: "Sukses",
  ),
  Quote(
    text: "Fokus pada akar, bukan buahnya. Perbaiki kualitas dirimu, maka hasil akan mengikuti.",
    textEn: "Focus on the root, not the fruit. Improve your self-quality, and the results will follow.",
    author: "Anonim",
    category: "Sukses",
  ),
];